/* Generated by scripts/generate-job-surface.py; do not edit. */

export type JobToolGroup = 'job_control' | 'job_inspection';
export type JobToolPlane =
  | 'job_control'
  | 'job_observability'
  | 'job_evidence'
  | 'job_workspace';
export type JobToolCaller = 'mcp' | 'officer' | 'session';

export interface GeneratedJobToolDescriptor {
  readonly name: string;
  readonly group: JobToolGroup;
  readonly plane: JobToolPlane;
  readonly callerDefaults: readonly JobToolCaller[];
  readonly grant: 'explicit' | null;
}

export interface GeneratedJobToolGroupMeta {
  readonly key: JobToolGroup;
  readonly label: string;
  readonly icon: string;
  readonly description: string;
}

export const JOB_TOOL_DESCRIPTORS: readonly GeneratedJobToolDescriptor[] = [
  {name: "acknowledge_job_message", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "approve_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "assign_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "cancel_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "create_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "delete_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "escalate_job_message", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_audit_bulk", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "get_audit_timerange", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "get_audit_trail", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_chat_bulk", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "get_chat_history", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_current_todos", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_frozen_job", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_job", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "get_job_completion_report", group: "job_inspection", plane: "job_evidence", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "get_job_diff", group: "job_inspection", plane: "job_workspace", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "get_job_file", group: "job_inspection", plane: "job_workspace", callerDefaults: ["mcp", "session"], grant: null},
  {name: "get_job_log", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_job_progress", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_job_summary", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_llm_request", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_message_thread", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_shell_state", group: "job_inspection", plane: "job_workspace", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "get_stuck_jobs", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_todo_archive", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_todos", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "get_workspace_overview", group: "job_inspection", plane: "job_workspace", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "list_job_commits", group: "job_inspection", plane: "job_workspace", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "list_job_evidence", group: "job_inspection", plane: "job_evidence", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "list_job_files", group: "job_inspection", plane: "job_workspace", callerDefaults: ["mcp", "session"], grant: null},
  {name: "list_jobs", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "list_llm_requests", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "list_message_threads", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "list_todo_archives", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "pause_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "promote_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp"], grant: "explicit"},
  {name: "read_job_evidence", group: "job_inspection", plane: "job_evidence", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "reply_to_job_message", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "resume_job_with_feedback", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer", "session"], grant: null},
  {name: "search_audit", group: "job_inspection", plane: "job_observability", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "send_message_to_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer"], grant: "explicit"},
  {name: "steer_job", group: "job_control", plane: "job_control", callerDefaults: ["mcp", "officer"], grant: "explicit"},
] as const;

export const JOB_TOOL_GROUP_CATEGORIES: readonly GeneratedJobToolGroupMeta[] = [
  {key: "job_control", label: "Job Control", icon: "play_circle", description: "Create, steer, pause, resume, approve, and cancel SRW jobs"},
  {key: "job_inspection", label: "Job Inspection", icon: "manage_search", description: "Inspect SRW job status and the currently granted supervision data"},
] as const;

export const JOB_TOOL_NAMES = new Set(
  JOB_TOOL_DESCRIPTORS.map(descriptor => descriptor.name),
);
