-- migration:     0007_thread_pk_identity.sql
-- description:   Convert the BIGSERIAL primary keys on thread_events and
--                thread_notifications to BIGINT GENERATED BY DEFAULT AS
--                IDENTITY columns.
--
--                Why: SQL:2003 identity columns are the modern preferred
--                form in Postgres for new auto-incrementing primary keys
--                (BIGSERIAL is a pseudotype retained for backward
--                compatibility). Functionally equivalent — both are an
--                auto-incrementing bigint backed by an internal sequence
--                — but identity columns track the sequence as part of
--                the column's metadata rather than as a separate sequence
--                object owned by the column. The sequence cannot be
--                detached, dropped, or reassigned independently of the
--                column it backs.
--
--                Originally these tables shipped with BIGSERIAL in 0004
--                and 0006. A subsequent commit attempted to modernize
--                the syntax by rewriting those files in place, which the
--                migration runner correctly rejected on checksum drift
--                (applied migrations are immutable). The intent of that
--                rewrite is preserved here as a forward migration; 0004
--                and 0006 have been restored to their originally-applied
--                BIGSERIAL form.
-- depends-on:    0006_headless_notifications.sql
-- expected:      < 1s regardless of row count. DROP DEFAULT, DROP
--                SEQUENCE, ADD GENERATED, and setval are all metadata-
--                only catalog operations.
-- locks:         AccessExclusiveLock briefly on each table per ALTER
--                (retried). Each owned sequence is dropped under its
--                own brief lock.
-- transactional: yes

BEGIN;
SET LOCAL lock_timeout                        = '2s';
SET LOCAL statement_timeout                   = '15min';
SET LOCAL idle_in_transaction_session_timeout = '5min';

-- thread_events.id : BIGSERIAL → IDENTITY
DO $$
DECLARE
    max_attempts CONSTANT int := 30;
    cap_ms       CONSTANT bigint := 60000;
    base_ms      CONSTANT bigint := 10;
    delay_ms              bigint;
    done                  boolean := false;
BEGIN
    FOR i IN 1..max_attempts LOOP
        BEGIN
            ALTER TABLE thread_events ALTER COLUMN id DROP DEFAULT;
            DROP SEQUENCE IF EXISTS thread_events_id_seq;
            ALTER TABLE thread_events
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            done := true;
            EXIT;
        EXCEPTION WHEN lock_not_available THEN
            delay_ms := round(random() * least(cap_ms, base_ms * 2 ^ i));
            PERFORM pg_sleep(delay_ms::numeric / 1000);
        END;
    END LOOP;
    IF NOT done THEN
        RAISE EXCEPTION
            'lock acquisition failed on thread_events after % attempts',
            max_attempts;
    END IF;
END $$;

-- Sync the new identity sequence to the existing max id so the next
-- INSERT does not collide. setval(..., false) makes the *next* nextval
-- return exactly the value passed.
SELECT setval(
    pg_get_serial_sequence('thread_events', 'id'),
    COALESCE((SELECT MAX(id) FROM thread_events), 0) + 1,
    false
);

-- thread_notifications.id : BIGSERIAL → IDENTITY
DO $$
DECLARE
    max_attempts CONSTANT int := 30;
    cap_ms       CONSTANT bigint := 60000;
    base_ms      CONSTANT bigint := 10;
    delay_ms              bigint;
    done                  boolean := false;
BEGIN
    FOR i IN 1..max_attempts LOOP
        BEGIN
            ALTER TABLE thread_notifications ALTER COLUMN id DROP DEFAULT;
            DROP SEQUENCE IF EXISTS thread_notifications_id_seq;
            ALTER TABLE thread_notifications
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            done := true;
            EXIT;
        EXCEPTION WHEN lock_not_available THEN
            delay_ms := round(random() * least(cap_ms, base_ms * 2 ^ i));
            PERFORM pg_sleep(delay_ms::numeric / 1000);
        END;
    END LOOP;
    IF NOT done THEN
        RAISE EXCEPTION
            'lock acquisition failed on thread_notifications after % attempts',
            max_attempts;
    END IF;
END $$;

SELECT setval(
    pg_get_serial_sequence('thread_notifications', 'id'),
    COALESCE((SELECT MAX(id) FROM thread_notifications), 0) + 1,
    false
);

COMMIT;
