"""Regression: a job description must not be able to corrupt the VM manifest.

A job description is free text — typed by users, generated by the loop engine
and automations. It is substituted into a JSON blob that lives inside the
`cloudInitNoCloud.userData: |` *block scalar* of the VM template, which makes
raw substitution fragile in two different ways:

  1. A newline (even a single trailing blank line) puts the continuation at
     column 1, which dedents out of the block scalar and terminates it. YAML
     then parses the description's tail as outer mapping keys and provisioning
     dies. Job 4435994d (2026-07-26) failed exactly this way — its description
     ended with a blank line.
  2. A `"` or `\\` does NOT break the YAML at all. The manifest applies, the VM
     boots, and job-config.json is corrupt — which management-daemon.py
     swallows with a log.warning, silently losing agent_config/vm_image/etc.
     A description shaped like indented YAML reaches the cloud-init structure
     the same way, producing a manifest that passes yaml.safe_load and is
     accepted by KubeVirt while its userData is malformed.

The parked external vm-controller render site remains covered. Same-cluster
mode no longer has a direct-K8s renderer and its job-config intentionally omits
the unused description field.

These tests render the REAL chart templates rather than a simplified fixture.
That is deliberate: the defect lives in the real template's *structure*, so the
hand-written stand-in templates in test_vm_provisioner.py and
test_vm_controller.py — which put the description in a plain flow scalar with
no block scalar and no JSON blob — cannot express it. They both have a
"special characters in description" test today, and both passed throughout.
"""

import json
import re
import sys
import textwrap
import types
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock

import pytest
import yaml

PROJECT_ROOT = Path(__file__).parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# KubeVirt's hard cap on an inline cloudInitNoCloud userData block. Documented
# in helm-vm-cluster/templates/vm-controller/configmap.yaml; exceeding it makes
# KubeVirt reject the VM.
USER_DATA_LIMIT = 2048

VM_CLUSTER_CHART = "helm-vm-cluster/templates/vm-controller/configmap.yaml"

JOB_CONFIG_PATH = "/run/agent/job-config.json"


# =============================================================================
# Loading the real template out of the Helm ConfigMap
# =============================================================================


def _load_chart_vm_template(rel_path: str) -> str:
    """Return the plain vm-template.yaml text embedded in a Helm ConfigMap.

    Drops Helm comment blocks, substitutes a dummy for remaining Helm value
    expressions, then extracts and dedents the `vm-template.yaml: |` block
    scalar — leaving exactly the text the provisioner loads at runtime, with
    its ${...} placeholders intact.
    """
    text = (PROJECT_ROOT / rel_path).read_text()
    # Helm comments — {{- /* ... */ -}} — may span lines.
    text = re.sub(r"\{\{-?\s*/\*.*?\*/\s*-?\}\}", "", text, flags=re.DOTALL)

    lines = text.splitlines()
    start = next(i for i, ln in enumerate(lines) if "vm-template.yaml: |" in ln) + 1

    # The block scalar runs until the first non-blank line that is not indented
    # past the block's own indentation (e.g. the chart's trailing {{- end }}).
    first_body = next(ln for ln in lines[start:] if ln.strip())
    indent = first_body[: len(first_body) - len(first_body.lstrip())]

    body = []
    for ln in lines[start:]:
        if ln.strip() and not ln.startswith(indent):
            break
        body.append(ln)

    template = textwrap.dedent("\n".join(body))
    # Any Helm value expression left inside the block (e.g. the SSH pubkey).
    return re.sub(
        r"\{\{.*?\}\}", "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIdummytestkey", template
    )


# =============================================================================
# Pulling the rendered cloud-init back apart
# =============================================================================


def _user_data(manifest: dict) -> str:
    """Extract the cloud-init userData text from a rendered VM manifest."""
    volumes = manifest["spec"]["template"]["spec"]["volumes"]
    cloud_init = next(v for v in volumes if "cloudInitNoCloud" in v)
    return cloud_init["cloudInitNoCloud"]["userData"]


def _job_config(manifest: dict) -> dict:
    """Parse /run/agent/job-config.json back out of a rendered VM manifest.

    Fails the test if the JSON is corrupt — that is the silent-corruption mode
    the escaping exists to prevent.
    """
    files = yaml.safe_load(_user_data(manifest))["write_files"]
    blob = next(f for f in files if f["path"] == JOB_CONFIG_PATH)["content"]
    try:
        return json.loads(blob)
    except json.JSONDecodeError as exc:
        pytest.fail(f"job-config.json is not valid JSON on the VM: {exc}\n{blob}")


def _write_file_paths(manifest: dict) -> list:
    return [f["path"] for f in yaml.safe_load(_user_data(manifest))["write_files"]]


def _runcmd(manifest: dict) -> list:
    return yaml.safe_load(_user_data(manifest)).get("runcmd", [])


# =============================================================================
# The external render site
# =============================================================================

BASE_JOB_CONFIG = {
    "job_id": "4435994d-b029-444d-8a3c-26c64abd456a",
    "agent_config": "designer",
    "vm_image": "ghcr.io/example/srw-agent-vm:v0.0.21",
    "cpu_cores": 8,
    "memory": "16Gi",
    "nats_url": "nats://srw-vm-nats.srw-vm.svc.cluster.local:4222",
}


def _install_controller_import_stubs() -> None:
    """Make `vm.controller.controller` importable outside its own image.

    It does `from headscale_client import HeadscaleClient` (only resolvable
    inside vm/controller/) and imports kubernetes + nats, none of which are
    installed in the test environment. Mirrors test_vm_controller.py.
    """
    headscale = types.ModuleType("headscale_client")
    headscale.HeadscaleClient = MagicMock()
    sys.modules.setdefault("headscale_client", headscale)

    k8s = types.ModuleType("kubernetes")
    k8s_client = types.ModuleType("kubernetes.client")
    k8s_config = types.ModuleType("kubernetes.config")
    k8s_exc = types.ModuleType("kubernetes.client.exceptions")

    class _FakeApiException(Exception):
        def __init__(self, status=500, body=""):
            self.status = status
            self.body = body
            super().__init__(f"{status}: {body}")

    k8s_exc.ApiException = _FakeApiException
    k8s_client.exceptions = k8s_exc
    k8s_client.CustomObjectsApi = MagicMock
    k8s_config.load_incluster_config = MagicMock()
    k8s.client = k8s_client
    k8s.config = k8s_config
    sys.modules.setdefault("kubernetes", k8s)
    sys.modules.setdefault("kubernetes.client", k8s_client)
    sys.modules.setdefault("kubernetes.config", k8s_config)
    sys.modules.setdefault("kubernetes.client.exceptions", k8s_exc)

    nats = types.ModuleType("nats")
    nats.connect = AsyncMock()
    sys.modules.setdefault("nats", nats)


def _controller_render(description: str) -> dict:
    """Render via the vm-controller running in the VM cluster."""
    _install_controller_import_stubs()
    from vm.controller.controller import VMController

    ctrl = VMController()
    ctrl.template_text = _load_chart_vm_template(VM_CLUSTER_CHART)
    return ctrl.render_template({**BASE_JOB_CONFIG, "description": description})


RENDER_SITES = [
    pytest.param(_controller_render, id="external-vm-controller"),
]


# =============================================================================
# Descriptions that must not be able to break provisioning
# =============================================================================

HOSTILE_DESCRIPTIONS = [
    # The actual failure: job 4435994d.
    pytest.param("Job 1C — Contemporary Hotel Neutral\n\n", id="trailing-blank-line"),
    # Survives a trailing-whitespace strip, so escaping is what saves this one.
    pytest.param(
        "Build the ERP.\n\nAcceptance:\n- billing\n- payroll", id="internal-newlines"
    ),
    pytest.param('Rename the "legacy" module', id="double-quote"),
    pytest.param("Handle C:\\Users paths", id="backslash"),
    pytest.param('Mix: "quoted"\nand \\ slashed\n', id="quotes-newlines-and-slashes"),
    pytest.param("Ship it — naïve ✅", id="unicode-is-harmless"),
    pytest.param("", id="empty"),
    pytest.param("   \n\n  ", id="whitespace-only"),
]


@pytest.mark.parametrize("render", RENDER_SITES)
@pytest.mark.parametrize("description", HOSTILE_DESCRIPTIONS)
def test_description_renders_a_parseable_manifest_and_job_config(render, description):
    """Any description yields valid YAML wrapping a valid job-config.json."""
    manifest = render(description)

    assert manifest["kind"] == "VirtualMachine"
    # The cloud-init must survive intact — the failure mode was the description
    # eating the rest of the block scalar.
    assert JOB_CONFIG_PATH in _write_file_paths(manifest)
    _job_config(manifest)  # fails the test if the JSON is corrupt


@pytest.mark.parametrize("render", RENDER_SITES)
@pytest.mark.parametrize("description", HOSTILE_DESCRIPTIONS)
def test_description_round_trips_into_job_config(render, description):
    """Escaping is lossless: the VM sees the description it was given."""
    manifest = render(description)

    assert _job_config(manifest)["description"] == description


@pytest.mark.parametrize("render", RENDER_SITES)
def test_description_cannot_restructure_cloud_init(render):
    """A description crafted as YAML cannot alter the VM's cloud-init.

    Descriptions are user-supplied, so raw substitution lets one reach the
    structure of the VM's own boot configuration. This payload is indented to
    match the cloud-init body and re-opens a block scalar to swallow the
    template text that follows it, which is nastier than the crash above: the
    *manifest* stays valid YAML, so it passes the provisioner's only check
    (yaml.safe_load) and KubeVirt accepts it — while the userData inside is
    corrupt, leaving a VM that boots with none of its configuration.
    """
    baseline = render("benign")
    attack = (
        "x\n"
        + " " * 16
        + "- path: /root/.ssh/authorized_keys\n"
        + " " * 18
        + "permissions: '0600'\n"
        + " " * 18
        + "content: ssh-ed25519 AAAAattacker\n"
        + " " * 18
        + "trailer: |"
    )

    manifest = render(attack)

    # userData must still be parseable cloud-init, structurally untouched.
    assert _write_file_paths(manifest) == _write_file_paths(baseline)
    assert _runcmd(manifest) == _runcmd(baseline)
    # The payload survives only as inert data inside the description value.
    # Escaping neutralizes structure; it does not delete content.
    assert _job_config(manifest)["description"] == attack


@pytest.mark.parametrize("render", RENDER_SITES)
def test_long_description_stays_within_kubevirt_user_data_limit(render):
    """A long description cannot push userData past KubeVirt's inline cap.

    Headroom is only ~350-450 bytes, and job descriptions routinely exceed
    that, so the description has to be bounded. The VM never reads this field —
    management-daemon.py is job-config.json's only consumer and ignores
    `description` — so truncating it costs nothing.
    """
    manifest = render("Build an ERP system. " * 500)

    user_data = _user_data(manifest)
    assert len(user_data.encode()) <= USER_DATA_LIMIT, (
        f"userData is {len(user_data.encode())} bytes, over KubeVirt's "
        f"{USER_DATA_LIMIT}-byte inline limit"
    )
    _job_config(manifest)  # still valid JSON after truncation


# =============================================================================
# Input hygiene at the job-creation choke point
# =============================================================================


@pytest.mark.asyncio
async def test_create_job_strips_surrounding_whitespace():
    """create_job normalizes the description before it is persisted.

    Defence in depth, not the fix: all six orchestrator entry points funnel
    through here, so a stray trailing blank line never reaches the database.
    Escaping at the render sites is what actually makes provisioning safe.
    """
    from orchestrator.database.postgres import PostgresDB

    db = PostgresDB.__new__(PostgresDB)
    conn = MagicMock()
    conn.fetchrow = AsyncMock(return_value={"id": "job-1", "status": "created"})

    acquired = MagicMock()
    acquired.__aenter__ = AsyncMock(return_value=conn)
    acquired.__aexit__ = AsyncMock(return_value=False)
    db.acquire = MagicMock(return_value=acquired)

    await db.create_job(description="  Job 1C — Contemporary Hotel Neutral\n\n  ")

    persisted_description = conn.fetchrow.await_args.args[1]
    assert persisted_description == "Job 1C — Contemporary Hotel Neutral"
