"""Typed, bounded inventory collectors for infrastructure metering."""

from .contracts import (
    CollectorLimits,
    InventoryError,
    InventoryScope,
    InventorySnapshot,
    KubernetesApiFailure,
    KubernetesListPage,
    KubernetesWatchEvent,
    RecoverableItemError,
    StagedInventoryItem,
    WatchEventType,
    WatchObservation,
    WatchOutcome,
    WatchQueueOverflow,
    normalized_payload,
)
from .kubernetes import KubernetesCollectionEngine, inventory_item_digest
from .kubernetes_client import RawKubernetesClient, RawKubernetesPodClient
from .storage_normalization import (
    NormalizedPV,
    NormalizedPVC,
    StorageNormalizationError,
    durable_volume_source_uid,
    normalize_persistent_volume,
    normalize_persistent_volume_claim,
    normalize_pv,
    normalize_pvc,
    volume_identity_key_fingerprint,
)

__all__ = [
    "CollectorLimits",
    "InventoryError",
    "InventoryScope",
    "InventorySnapshot",
    "KubernetesApiFailure",
    "KubernetesCollectionEngine",
    "KubernetesListPage",
    "KubernetesWatchEvent",
    "NormalizedPV",
    "NormalizedPVC",
    "RawKubernetesClient",
    "RawKubernetesPodClient",
    "RecoverableItemError",
    "StagedInventoryItem",
    "StorageNormalizationError",
    "WatchEventType",
    "WatchObservation",
    "WatchOutcome",
    "WatchQueueOverflow",
    "inventory_item_digest",
    "durable_volume_source_uid",
    "normalize_persistent_volume",
    "normalize_persistent_volume_claim",
    "normalized_payload",
    "normalize_pv",
    "normalize_pvc",
    "volume_identity_key_fingerprint",
]
