{{- if .Values.sessionRouter.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sessionRouter.jwtSecretName | default (printf "%s-session-jwt" (include "srw.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srw.componentLabels" (dict "context" . "component" "orchestrator") | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.sessionRouter.jwtSecret | quote }}
{{- end }}
