"""VM Provisioner — Unified VM lifecycle management.

Four backends, auto-selected based on available infrastructure:

1. **NATS bridge** (cross-cluster): Publishes to NATS, VM Controller on remote
   agent cluster handles KubeVirt API calls. Used when NATS_URL is configured.

2. **HTTP controller** (same-cluster): POSTs to a co-located VM Controller
   over HTTP. The controller still owns KubeVirt RBAC and the VM template;
   only the transport changes. Used when VM_CONTROLLER_URL is configured.

3. **Direct K8s API** (same-cluster, no controller): Orchestrator calls
   KubeVirt API directly. Requires VM_TEMPLATE_PATH + kubevirt.io RBAC on
   the orchestrator's ServiceAccount.

4. **Docker** (compose): QEMU-in-Docker pool, see docker_provisioner.py.

Selection priority:
  NATS_URL set       → NATS mode
  VM_CONTROLLER_URL  → HTTP mode
  template + k8s     → direct mode
  docker hosts       → docker mode
  none               → VM features disabled

The VM endpoints and lifecycle hooks in main.py use this provisioner exclusively.
"""

import asyncio
from collections.abc import Mapping
from dataclasses import dataclass
import json
import logging
import os
import time
from typing import Any, Optional
from uuid import UUID, uuid4

import httpx

from services.workspace_binding import CANVAS_WORKSPACE_GENERATION_KEY
import yaml

from .nats_bridge import nats_bridge
from .vm_lifecycle_auth import (
    AUTH_FIELD,
    configured_secret,
    sign_payload,
    unsigned_payload,
    verify_payload,
)

try:
    from kubernetes import client as k8s_client, config as k8s_config

    K8S_AVAILABLE = True
except ImportError:
    k8s_client = None
    k8s_config = None
    K8S_AVAILABLE = False

logger = logging.getLogger(__name__)

# KubeVirt API coordinates (same as vm/controller/controller.py)
KUBEVIRT_GROUP = "kubevirt.io"
KUBEVIRT_VERSION = "v1"
KUBEVIRT_PLURAL = "virtualmachines"

VM_ROOTDISK_PVC_UID_ATTEMPTS = int(os.environ.get("VM_ROOTDISK_PVC_UID_ATTEMPTS", "20"))
VM_ROOTDISK_PVC_UID_RETRY_SECONDS = float(
    os.environ.get("VM_ROOTDISK_PVC_UID_RETRY_SECONDS", "0.25")
)


# The job description is free text — typed by users, generated by the loop
# engine and automations — and lands in a JSON blob nested inside the VM
# template's cloud-init `userData: |` block scalar. Raw substitution there is
# unsafe twice over: a newline puts the continuation at column 1, dedenting out
# of the block scalar and destroying the manifest (job 4435994d), while a quote
# or backslash leaves valid YAML wrapping a corrupt job-config.json that
# management-daemon.py discards with only a log.warning.
#
# Capped because the whole userData block has a hard 2048-byte KubeVirt limit
# (inline cloudInitNoCloud) with only ~350 bytes of headroom. Nothing in the VM
# reads this field — management-daemon.py is job-config.json's only consumer and
# never looks at `description` — so truncating it costs nothing.
MAX_DESCRIPTION_LEN = 200

_OWNER_KINDS = frozenset({"job", "thread"})
_PROVISION_GENERATION_ANNOTATION = "srw.io/provision-generation"


@dataclass(frozen=True, slots=True)
class VMTeardownIdentity:
    """Immutable VM incarnation captured before a destructive lifecycle call."""

    provision_generation: str
    vm_uid: str | None
    rootdisk_pvc_uid: str | None


@dataclass(frozen=True, slots=True)
class VMTeardownResult:
    """Bounded result distinguishing completion from identity supersession."""

    disposition: str
    deleted: bool


@dataclass(frozen=True, slots=True)
class _VMTeardownProbe:
    """Authenticated observation used to reconcile an ambiguous delete."""

    disposition: str
    identity: VMTeardownIdentity | None = None
    rootdisk_identity_known: bool = False


def _escape_for_job_config(description: str) -> str:
    """JSON-escape a description for the template's job-config.json blob.

    Returns the escaped body without json.dumps' surrounding quotes, since the
    template supplies those. Shrinks the raw text until its *escaped* form fits
    MAX_DESCRIPTION_LEN, so an escape sequence is never cut in half.
    """
    raw = description[:MAX_DESCRIPTION_LEN]
    while raw and len(json.dumps(raw)[1:-1]) > MAX_DESCRIPTION_LEN:
        raw = raw[:-1]
    return json.dumps(raw)[1:-1]


def _owner_identity(job_config: dict) -> tuple[str, str]:
    """Return the validated, full application owner identity for one VM."""

    owner_kind = job_config.get("entity_type", "job")
    owner_id = job_config.get("job_id")
    if owner_kind not in _OWNER_KINDS:
        raise ValueError("entity_type must be 'job' or 'thread'")
    if (
        not isinstance(owner_id, str)
        or not owner_id
        or owner_id != owner_id.strip()
        or len(owner_id) > 63
        or any(character.isspace() for character in owner_id)
    ):
        raise ValueError("job_id is not a valid Kubernetes owner label")
    return owner_kind, owner_id


def _stamp_owner_identity(manifest: dict, owner_kind: str, owner_id: str) -> None:
    """Stamp VM, VMI-template, and DataVolume/PVC-propagated owner labels."""

    def stamp(metadata: dict) -> None:
        labels = metadata.setdefault("labels", {})
        labels["srw.io/owner-kind"] = owner_kind
        labels["srw.io/owner-id"] = owner_id

    stamp(manifest.setdefault("metadata", {}))
    spec = manifest.setdefault("spec", {})
    template = spec.setdefault("template", {})
    stamp(template.setdefault("metadata", {}))
    data_volume_templates = spec.get("dataVolumeTemplates", [])
    if isinstance(data_volume_templates, list):
        for data_volume_template in data_volume_templates:
            if isinstance(data_volume_template, dict):
                stamp(data_volume_template.setdefault("metadata", {}))


def _provision_generation(value: object) -> str | None:
    if not isinstance(value, str) or len(value) != 36:
        return None
    try:
        parsed = UUID(value)
    except (AttributeError, TypeError, ValueError):
        return None
    return value if str(parsed) == value else None


def _stamp_provision_generation(manifest: dict, generation: str) -> None:
    metadata = manifest.setdefault("metadata", {})
    metadata.setdefault("annotations", {})[_PROVISION_GENERATION_ANNOTATION] = (
        generation
    )
    template_metadata = (
        manifest.setdefault("spec", {})
        .setdefault("template", {})
        .setdefault("metadata", {})
    )
    template_metadata.setdefault("annotations", {})[
        _PROVISION_GENERATION_ANNOTATION
    ] = generation


def _admitted_provision_generation(value: object) -> str | None:
    if not isinstance(value, Mapping):
        return None
    metadata = value.get("metadata")
    if not isinstance(metadata, Mapping):
        return None
    annotations = metadata.get("annotations")
    if not isinstance(annotations, Mapping):
        return None
    return _provision_generation(annotations.get(_PROVISION_GENERATION_ANNOTATION))


def _safe_vm_uid(value: object) -> str | None:
    if (
        not isinstance(value, str)
        or not value
        or value != value.strip()
        or len(value) > 256
        or any(character.isspace() for character in value)
    ):
        return None
    return value


def _admitted_vm_uid(value: object, *, expected_name: str) -> str | None:
    """Extract the immutable VM UID from one admitted Kubernetes object."""

    if not isinstance(value, Mapping):
        return None
    metadata = value.get("metadata")
    if not isinstance(metadata, Mapping) or metadata.get("name") != expected_name:
        return None
    return _safe_vm_uid(metadata.get("uid"))


def _admitted_pvc_uid(
    value: object,
    *,
    expected_name: str,
    expected_owner_id: str,
    expected_owner_kind: str,
) -> str | None:
    """Extract an immutable UID only from the exact provisioned root claim."""

    if isinstance(value, Mapping):
        metadata = value.get("metadata")
    else:
        metadata = getattr(value, "metadata", None)
    if isinstance(metadata, Mapping):
        name = metadata.get("name")
        uid = metadata.get("uid")
        labels = metadata.get("labels")
    else:
        name = getattr(metadata, "name", None)
        uid = getattr(metadata, "uid", None)
        labels = getattr(metadata, "labels", None)
    if name != expected_name or not isinstance(labels, Mapping):
        return None
    if (
        labels.get("srw.io/owner-kind") != expected_owner_kind
        or labels.get("srw.io/owner-id") != expected_owner_id
    ):
        return None
    return _safe_vm_uid(uid)


def _extract_vm_context(job: dict) -> dict:
    """Extract the vm sub-dict from a job's context."""
    ctx = job.get("context") or {}
    if isinstance(ctx, str):
        try:
            ctx = json.loads(ctx)
        except (json.JSONDecodeError, TypeError):
            ctx = {}
    return ctx.get("vm", {})


def _http_lifecycle_query(
    payload: Mapping[str, Any], *, operation: str, secret: bytes | None
) -> dict[str, str]:
    """Encode an authenticated envelope into stable HTTP query fields."""

    signed = sign_payload(
        payload,
        direction="request",
        operation=operation,
        secret=secret,
    )
    auth = signed.get(AUTH_FIELD)
    if not isinstance(auth, Mapping):
        return {}
    return {
        "lifecycle_auth": str(auth["signature"]),
        "lifecycle_auth_issued_at": str(auth["issued_at"]),
        "lifecycle_auth_request_id": str(auth["request_id"]),
    }


def vm_persistent_rootdisk_enabled() -> bool:
    """Whether the VM controller keeps rootdisks across VM deletion.

    Mirrors the controller's own ``VM_PERSISTENT_ROOTDISK``; the orchestrator
    cannot observe the controller's config, so the two are set from the same
    Helm value and this is the orchestrator's copy. Read at call time rather
    than import so tests (and a config reload) see changes.

    **Enable the controller first.** Turning this on against a controller that
    still cascade-deletes disks would let VM session suspend tear a workspace
    down believing the files survive — they would not. The reverse order is
    harmless: the controller keeps disks nobody asks it to keep, and the
    delete-status handler records what actually happened either way.

    knowledge-base/knowledge/features/vm_persistent_rootdisk.md
    """
    return os.environ.get("VM_PERSISTENT_ROOTDISK", "false").strip().lower() in (
        "1",
        "true",
        "yes",
    )


class VMProvisioner:
    """Unified VM provisioner with automatic backend selection.

    Uses NATS bridge when available (cross-cluster), falls back to direct
    Kubernetes API calls (same-cluster). Control commands (freeze/resume/
    terminate) require NATS since they target the management daemon inside
    the VM.
    """

    def __init__(self):
        self._db: Optional[Any] = None
        self._snapshot_service: Optional[Any] = None
        self._k8s: Optional[Any] = None
        self._core_k8s: Optional[Any] = None
        self._k8s_available: bool = False
        self._template_text: str = ""
        self._vm_namespace: str = os.environ.get("VM_NAMESPACE", "agent-vms")
        self._default_vm_image: str = os.environ.get(
            "DEFAULT_VM_IMAGE",
            "ghcr.io/knaeckebrothero/superhuman-remote-worker-agent-vm-base:latest",
        )
        # HTTP controller transport (same-cluster, no NATS).
        self._controller_url: str = os.environ.get("VM_CONTROLLER_URL", "").rstrip("/")
        self._http_client: Optional[httpx.AsyncClient] = None
        self._http_timeout: float = float(os.environ.get("VM_CONTROLLER_TIMEOUT", "30"))
        self._lifecycle_hmac_secret = configured_secret()

    @property
    def is_available(self) -> bool:
        """True if any VM provisioning backend is available."""
        return (
            nats_bridge.is_available
            or self._http_available
            or self._k8s_available
            or self._docker_available
        )

    @property
    def _http_available(self) -> bool:
        """True if a co-located VM controller HTTP endpoint is configured."""
        return bool(self._controller_url)

    @property
    def _docker_available(self) -> bool:
        """True if QEMU-in-Docker VMs are configured."""
        from .docker_provisioner import docker_provisioner

        return len(docker_provisioner.vm_hosts) > 0

    @property
    def mode(self) -> Optional[str]:
        """Current provisioning mode: 'nats', 'http', 'direct', 'docker', or None."""
        if nats_bridge.is_available:
            return "nats"
        if self._http_available:
            return "http"
        if self._k8s_available:
            return "direct"
        if self._docker_available:
            return "docker"
        return None

    async def _current_provision_generation(
        self, entity_type: str, entity_id: str
    ) -> str | None:
        """Read the durable generation used to fence lifecycle commands."""

        if not self._db:
            return None
        try:
            if entity_type == "thread":
                row = await self._db.get_thread(entity_id)
                metadata = row.get("metadata") if isinstance(row, Mapping) else None
                if isinstance(metadata, str):
                    metadata = json.loads(metadata)
                context = metadata.get("vm") if isinstance(metadata, Mapping) else None
            else:
                row = await self._db.get_job(entity_id)
                context = _extract_vm_context(row) if isinstance(row, dict) else None
            if not isinstance(context, Mapping):
                return None
            return _provision_generation(context.get("provision_generation"))
        except Exception:
            logger.exception(
                "Could not read current VM provision generation for %s %s",
                entity_type,
                entity_id,
            )
            return None

    async def _set_context_if_generation(
        self,
        entity_type: str,
        entity_id: str,
        generation: str,
        updates: dict,
    ) -> bool:
        if entity_type == "thread":
            return await self._set_thread_vm_context_if_generation(
                entity_id, generation, updates
            )
        return await self._set_vm_context_if_generation(entity_id, generation, updates)

    async def _persist_status_identity(
        self, entity_type: str, entity_id: str, data: Mapping[str, Any]
    ) -> bool:
        """Persist query-discovered identities only from authenticated evidence."""

        if data.get("_identity_authenticated") is not True:
            return False
        generation = _provision_generation(data.get("provision_generation"))
        if generation is None:
            return False
        updates: dict[str, Any] = {}
        for key in ("vm_name", "namespace"):
            if isinstance(data.get(key), str):
                updates[key] = data[key]
        vm_uid = _safe_vm_uid(data.get("vm_uid"))
        if vm_uid is not None:
            updates.update(
                {
                    "vm_uid": vm_uid,
                    "identity_authenticated": True,
                    "identity_provision_generation": generation,
                }
            )
        if (root_uid := _safe_vm_uid(data.get("rootdisk_pvc_uid"))) is not None:
            updates["rootdisk_pvc_uid"] = root_uid
        return await self._set_context_if_generation(
            entity_type,
            entity_id,
            generation,
            updates,
        )

    # =========================================================================
    # Lifecycle
    # =========================================================================

    def connect(
        self,
        db: Any,
        snapshot_service: Optional[Any] = None,
    ) -> None:
        """Initialize the provisioner.

        Args:
            db: PostgresDB instance for job context updates.
            snapshot_service: Optional SnapshotService for archival before deletion.
        """
        self._db = db
        self._snapshot_service = snapshot_service
        self._init_k8s()

        if self._http_available:
            self._http_client = httpx.AsyncClient(
                base_url=self._controller_url,
                timeout=self._http_timeout,
            )

        if nats_bridge.is_available:
            logger.info("VM provisioner ready: NATS mode")
        elif self._http_available:
            logger.info(
                "VM provisioner ready: HTTP mode (controller=%s)",
                self._controller_url,
            )
        elif self._k8s_available:
            logger.info(
                "VM provisioner ready: direct K8s mode (namespace=%s)",
                self._vm_namespace,
            )
        else:
            logger.info(
                "VM provisioner: no backend available "
                "(NATS, controller URL, and K8s all unavailable)"
            )

    async def disconnect(self) -> None:
        """Close the HTTP client (if any)."""
        if self._http_client is not None:
            try:
                await self._http_client.aclose()
            except Exception:
                logger.debug("Error closing VM controller HTTP client", exc_info=True)
            self._http_client = None

    def _init_k8s(self) -> None:
        """Try to initialize the Kubernetes client for direct provisioning."""
        if not K8S_AVAILABLE:
            return

        try:
            try:
                k8s_config.load_incluster_config()
            except k8s_config.ConfigException:
                try:
                    k8s_config.load_kube_config()
                except k8s_config.ConfigException:
                    logger.debug(
                        "Kubernetes not available (no in-cluster or kubeconfig)"
                    )
                    return

            self._k8s = k8s_client.CustomObjectsApi()
            self._core_k8s = k8s_client.CoreV1Api()
            self._load_template()
        except Exception as e:
            logger.debug("Direct K8s VM provisioning not available: %s", e)
            self._k8s = None
            self._core_k8s = None
            self._k8s_available = False

    def _load_template(self) -> None:
        """Load the KubeVirt VM template for direct provisioning."""
        path = os.environ.get("VM_TEMPLATE_PATH", "")
        if not path:
            for candidate in [
                "/config/vm-template.yaml",
                "deployment/harvester/vm-template.yaml",
            ]:
                if os.path.exists(candidate):
                    path = candidate
                    break

        if not path or not os.path.exists(path):
            logger.info("VM template not found — direct K8s provisioning disabled")
            self._k8s = None
            self._core_k8s = None
            self._k8s_available = False
            return

        with open(path) as f:
            self._template_text = f.read()

        self._k8s_available = True
        logger.info("Loaded VM template from %s", path)

    def _render_template(self, job_config: dict) -> dict:
        """Render the VM template with job-specific values.

        Same string substitution as vm/controller/controller.py.
        """
        owner_kind, owner_id = _owner_identity(job_config)
        replacements = {
            # NOTE: keep _escape_for_job_config() in sync with the copy in
            # vm/controller/controller.py — separate images, no shared code.
            "${JOB_ID}": job_config["job_id"],
            "${OWNER_KIND}": owner_kind,
            "${OWNER_ID}": owner_id,
            "${AGENT_CONFIG}": job_config.get("agent_config", "worker_base"),
            "${VM_IMAGE}": job_config.get("vm_image") or self._default_vm_image,
            "${CPU_CORES}": str(job_config.get("cpu_cores", 8)),
            "${MEMORY}": job_config.get("memory", "16Gi"),
            "${NATS_URL}": job_config.get("nats_url", ""),
            # Direct mode has no VM controller to inject the deployment identity
            # and mesh settings. Read the same existing environment contract the
            # controller/agent provisioners use. An empty Tailscale key is valid:
            # the cloud-init command is explicitly gated on a non-empty value,
            # which is the co-located, no-mesh deployment path.
            "${ORCHESTRATOR_ID}": os.environ.get("ORCHESTRATOR_ID", "").strip(),
            "${HEADSCALE_URL}": os.environ.get("HEADSCALE_URL", ""),
            "${TAILSCALE_AUTH_KEY}": os.environ.get("TAILSCALE_AUTH_KEY", ""),
            "${DESCRIPTION}": _escape_for_job_config(job_config.get("description", "")),
            # CDI DataVolume storage
            "${VM_STORAGE_CLASS}": os.environ.get("VM_STORAGE_CLASS", "local-path"),
            "${VM_DISK_SIZE}": os.environ.get("VM_DISK_SIZE", "20Gi"),
        }

        rendered = self._template_text
        for placeholder, value in replacements.items():
            rendered = rendered.replace(placeholder, value)

        manifest = yaml.safe_load(rendered)
        _stamp_owner_identity(manifest, owner_kind, owner_id)
        if generation := _provision_generation(job_config.get("provision_generation")):
            _stamp_provision_generation(manifest, generation)
        return manifest

    async def _set_vm_context_if_generation(
        self, job_id: str, generation: str, updates: dict
    ) -> bool:
        if not self._db:
            return False
        try:
            return bool(
                await self._db.merge_vm_context_if_provision_generation(
                    job_id, generation, updates
                )
            )
        except Exception:
            logger.exception(
                "Failed to update generation-guarded VM context for job %s", job_id
            )
            return False

    # =========================================================================
    # Public API
    # =========================================================================

    async def create_vm(
        self,
        job_id: str,
        agent_config: str = "worker_base",
        vm_image: Optional[str] = None,
        cpu_cores: int = 8,
        memory: str = "16Gi",
        description: str = "",
        fresh: bool = True,
    ) -> bool:
        """Create a VM for a job.

        Picks the highest-priority transport that is available
        (NATS > HTTP > direct > docker).

        Args:
            fresh: True (default) for a genuine (re)provision. False for a
                deferred-create poll re-issue — the controller answered
                ``waiting_golden`` (a shared golden image is importing) or
                ``waiting_headscale`` (the mesh VPN is down, so a VM would be
                unreachable), no VM exists yet, and the dispatcher re-sends
                create as the poll. A poll must NOT reset the provision
                context: ``golden_wait_started_at`` /
                ``headscale_wait_started_at`` anchor those budgets across
                polls, and the context status must stay ``waiting_*`` (not
                flip to 'provisioning') so the decision logic keeps polling
                instead of burning boot-budget waits.
                ``provisioned_at`` alone is rolled forward so that when the
                golden completes and the create finally builds the VM, the boot
                budget starts from ≈ that moment, not from the first poll.

        Returns:
            True if the request was accepted, False otherwise.
        """
        # A (re)provisioned VM must start with a CLEAN reap counter and no stale
        # SSH endpoint. context.vm is *merged* (not replaced) across provisions,
        # so a prior incarnation's snapshot_attempts — which reaches the reaper's
        # max and makes attempts_exhausted instantly true, force-deleting the new
        # VM on its first tick — and its dead ssh_host would otherwise leak into
        # this fresh VM. provisioned_at anchors the dispatcher's provisioning
        # timeout. Runs before backend dispatch so every transport inherits it.
        if fresh:
            fresh_context = self._fresh_provision_ctx()
            generation = fresh_context["provision_generation"]
            await self._set_vm_context(job_id, fresh_context)
        else:
            await self._set_vm_context(job_id, {"provisioned_at": time.time()})
            generation = await self._current_provision_generation("job", job_id)
        if nats_bridge.is_available:
            return await nats_bridge.request_vm_create(
                job_id=job_id,
                agent_config=agent_config,
                vm_image=vm_image,
                cpu_cores=cpu_cores,
                memory=memory,
                description=description,
                entity_type="job",
                set_provisioning=fresh,
                provision_generation=generation,
            )

        if self._http_available:
            return await self._create_http(
                job_id=job_id,
                agent_config=agent_config,
                vm_image=vm_image,
                cpu_cores=cpu_cores,
                memory=memory,
                description=description,
                entity_type="job",
                set_provisioning=fresh,
                provision_generation=generation,
            )

        if self._k8s_available:
            return await self._create_direct(
                job_id=job_id,
                agent_config=agent_config,
                vm_image=vm_image,
                cpu_cores=cpu_cores,
                memory=memory,
                description=description,
                provision_generation=generation,
            )

        # Docker Compose mode: assign from QEMU-in-Docker pool
        if self._docker_available:
            from .docker_provisioner import docker_provisioner

            result = await docker_provisioner.assign_vm(job_id)
            return result is not None

        return False

    async def capture_vm_teardown_identity(self, job_id: str) -> VMTeardownIdentity:
        """Capture one authenticated VM generation/UID tuple for replay.

        The provision generation is mandatory on every backend.  Immutable VM
        and rootdisk UIDs are included only when the controller/direct API has
        authenticated them for that exact generation; an unauthenticated guest
        report can never become teardown authority.
        """

        if not self._db:
            raise RuntimeError("VM teardown identity database is unavailable")
        row = await self._db.get_job(job_id)
        if not isinstance(row, dict):
            raise RuntimeError("VM teardown job no longer exists")
        context = _extract_vm_context(row)
        generation = _provision_generation(context.get("provision_generation"))
        if generation is None:
            raise RuntimeError("VM teardown provision generation is unavailable")

        authenticated = (
            context.get("identity_authenticated") is True
            and _provision_generation(context.get("identity_provision_generation"))
            == generation
        )
        vm_uid = _safe_vm_uid(context.get("vm_uid")) if authenticated else None
        rootdisk_uid = (
            _safe_vm_uid(context.get("rootdisk_pvc_uid")) if authenticated else None
        )
        if vm_uid is None or rootdisk_uid is None:
            probe = await self._probe_vm_teardown_identity(job_id, generation)
            if probe.disposition == "unknown":
                raise RuntimeError("VM teardown identity probe is unavailable")
            if probe.disposition == "superseded":
                raise RuntimeError("VM teardown provision generation changed")
            if probe.identity is not None:
                probed_vm_uid = probe.identity.vm_uid
                probed_rootdisk_uid = probe.identity.rootdisk_pvc_uid
                if (
                    vm_uid is not None
                    and probed_vm_uid is not None
                    and vm_uid != probed_vm_uid
                ) or (
                    rootdisk_uid is not None
                    and probe.rootdisk_identity_known
                    and rootdisk_uid != probed_rootdisk_uid
                ):
                    raise RuntimeError("VM teardown immutable identity changed")
                if vm_uid is None:
                    vm_uid = probed_vm_uid
                if rootdisk_uid is None and probe.rootdisk_identity_known:
                    rootdisk_uid = probed_rootdisk_uid
            if probe.disposition == "present" and (
                not probe.rootdisk_identity_known or rootdisk_uid is None
            ):
                raise RuntimeError("VM teardown rootdisk identity is unavailable")
        return VMTeardownIdentity(
            provision_generation=generation,
            vm_uid=vm_uid,
            rootdisk_pvc_uid=rootdisk_uid,
        )

    async def _probe_vm_teardown_identity(
        self,
        job_id: str,
        generation: str,
    ) -> _VMTeardownProbe:
        """Probe the exact backend without collapsing absence into transport loss."""

        result: Mapping[str, Any] | None
        if nats_bridge.is_available:
            result = await nats_bridge.query_vm_status(
                job_id,
                provision_generation=generation,
                exact_absence=True,
            )
        elif self._http_available:
            result = await self._query_http(
                job_id,
                provision_generation=generation,
                exact_absence=True,
            )
        elif self._k8s_available:
            result = await self._query_direct(
                job_id,
                entity_type="job",
                absent_generation=generation,
            )
        else:
            return _VMTeardownProbe("unknown")

        if not isinstance(result, Mapping):
            return _VMTeardownProbe("unknown")
        if result.get("_identity_authenticated") is not True:
            return _VMTeardownProbe("unknown")
        observed_generation = _provision_generation(result.get("provision_generation"))
        if observed_generation != generation:
            return _VMTeardownProbe("superseded")
        status = str(result.get("status") or "")
        rootdisk_known = result.get("rootdisk_identity_known") is True
        identity = VMTeardownIdentity(
            provision_generation=generation,
            vm_uid=_safe_vm_uid(result.get("vm_uid")),
            rootdisk_pvc_uid=_safe_vm_uid(result.get("rootdisk_pvc_uid")),
        )
        if status == "not_found":
            return _VMTeardownProbe(
                "absent",
                identity,
                rootdisk_identity_known=rootdisk_known,
            )
        if status in {"query_failed", "delete_failed"} or identity.vm_uid is None:
            return _VMTeardownProbe("unknown")
        return _VMTeardownProbe(
            "present",
            identity,
            rootdisk_identity_known=rootdisk_known,
        )

    async def revalidate_vm_teardown_identity(
        self,
        job_id: str,
        identity: VMTeardownIdentity,
    ) -> str:
        """Re-prove an exact VM incarnation immediately before snapshot I/O."""

        generation = _provision_generation(identity.provision_generation)
        if generation is None:
            return "unknown"
        if await self._current_provision_generation("job", job_id) != generation:
            return "superseded"
        probe = await self._probe_vm_teardown_identity(job_id, generation)
        classification = self._classify_captured_probe(probe, identity, purge_disk=True)
        if classification == "matched":
            return "matched"
        if classification in {"superseded", "completed"}:
            return "superseded"
        return "unknown"

    @staticmethod
    def _classify_captured_probe(
        probe: _VMTeardownProbe,
        identity: VMTeardownIdentity,
        *,
        purge_disk: bool = True,
    ) -> str:
        """Map one authenticated observation to completed/matched/superseded."""

        if probe.disposition in {"unknown", "superseded"}:
            return probe.disposition
        current = probe.identity
        if current is None:
            return "unknown"
        if probe.disposition == "present":
            if identity.vm_uid is None or current.vm_uid != identity.vm_uid:
                return "superseded"
            if purge_disk:
                if not probe.rootdisk_identity_known:
                    return "unknown"
                if identity.rootdisk_pvc_uid is None:
                    return "unknown"
                if current.rootdisk_pvc_uid != identity.rootdisk_pvc_uid:
                    return "superseded"
            return "matched"
        if not probe.rootdisk_identity_known:
            return "unknown"
        if current.rootdisk_pvc_uid is None:
            # VM and rootdisk both proven absent: a lost delete response is
            # exact idempotent success even when DB context is still stale.
            return "completed"
        if identity.rootdisk_pvc_uid is None:
            return "unknown"
        if current.rootdisk_pvc_uid != identity.rootdisk_pvc_uid:
            return "superseded"
        return "matched" if purge_disk else "completed"

    async def delete_vm_captured(
        self,
        job_id: str,
        identity: VMTeardownIdentity,
        *,
        purge_disk: bool = True,
    ) -> VMTeardownResult:
        """Delete only the VM/rootdisk incarnation captured in an intent."""

        generation = _provision_generation(identity.provision_generation)
        if generation is None:
            return VMTeardownResult("identity_invalid", False)
        current_generation = await self._current_provision_generation("job", job_id)
        if current_generation != generation:
            return VMTeardownResult("identity_superseded", False)
        probe = await self._probe_vm_teardown_identity(job_id, generation)
        classification = self._classify_captured_probe(
            probe, identity, purge_disk=purge_disk
        )
        if classification == "superseded":
            return VMTeardownResult("identity_superseded", False)
        if classification == "completed":
            return VMTeardownResult("completed", True)
        if classification != "matched":
            return VMTeardownResult("identity_unknown", False)
        await self._delete_vm_with_identity(
            job_id,
            purge_disk=purge_disk,
            provision_generation=generation,
            expected_vm_uid=_safe_vm_uid(identity.vm_uid),
            expected_rootdisk_pvc_uid=_safe_vm_uid(identity.rootdisk_pvc_uid),
        )
        reprobe = await self._probe_vm_teardown_identity(job_id, generation)
        reclassification = self._classify_captured_probe(
            reprobe, identity, purge_disk=purge_disk
        )
        if reclassification == "completed":
            return VMTeardownResult("completed", True)
        if reclassification == "superseded":
            return VMTeardownResult("identity_superseded", False)
        return VMTeardownResult("retry_pending", False)

    async def release_vm_captured(
        self,
        job_id: str,
        identity: VMTeardownIdentity,
        *,
        ssh_host: str | None = None,
        ssh_port: int | None = None,
    ) -> VMTeardownResult:
        """Best-effort archive, then release only the captured VM incarnation."""

        generation = _provision_generation(identity.provision_generation)
        if generation is None:
            return VMTeardownResult("identity_invalid", False)
        if await self._current_provision_generation("job", job_id) != generation:
            return VMTeardownResult("identity_superseded", False)
        probe = await self._probe_vm_teardown_identity(job_id, generation)
        classification = self._classify_captured_probe(probe, identity, purge_disk=True)
        if classification == "superseded":
            return VMTeardownResult("identity_superseded", False)
        if classification == "completed":
            return VMTeardownResult("completed", True)
        if classification != "matched":
            return VMTeardownResult("identity_unknown", False)

        if (
            self._snapshot_service
            and self._snapshot_service.is_available
            and ssh_host
            and ssh_port
        ):
            try:
                captured = await self._snapshot_service.capture_vm_snapshot(
                    job_id=job_id,
                    ssh_host=ssh_host,
                    ssh_port=int(ssh_port),
                    source_type="vm",
                )
                if not captured:
                    logger.warning(
                        "Captured VM snapshot skipped for job %s; deleting exact "
                        "incarnation under terminal teardown policy",
                        job_id,
                    )
            except Exception:
                logger.exception(
                    "Captured VM snapshot failed for job %s; deleting exact "
                    "incarnation under terminal teardown policy",
                    job_id,
                )
        return await self.delete_vm_captured(job_id, identity, purge_disk=True)

    async def delete_orphan_vm_captured(
        self,
        job_id: str,
        identity: VMTeardownIdentity,
        *,
        purge_disk: bool = True,
    ) -> VMTeardownResult:
        """Delete an inventory-proven VM after both owning rows are absent."""

        generation = _provision_generation(identity.provision_generation)
        vm_uid = _safe_vm_uid(identity.vm_uid)
        rootdisk_uid = _safe_vm_uid(identity.rootdisk_pvc_uid)
        if (
            generation is None
            or vm_uid is None
            or (purge_disk and rootdisk_uid is None)
        ):
            return VMTeardownResult("identity_unknown", False)
        probe = await self._probe_vm_teardown_identity(job_id, generation)
        classification = self._classify_captured_probe(
            probe, identity, purge_disk=purge_disk
        )
        if classification == "completed":
            return VMTeardownResult("completed", True)
        if classification == "superseded":
            return VMTeardownResult("identity_superseded", False)
        if classification != "matched":
            return VMTeardownResult("identity_unknown", False)
        await self._delete_vm_with_identity(
            job_id,
            purge_disk=purge_disk,
            provision_generation=generation,
            expected_vm_uid=vm_uid,
            expected_rootdisk_pvc_uid=rootdisk_uid,
        )
        reprobe = await self._probe_vm_teardown_identity(job_id, generation)
        reclassification = self._classify_captured_probe(
            reprobe, identity, purge_disk=purge_disk
        )
        if reclassification == "completed":
            return VMTeardownResult("completed", True)
        if reclassification == "superseded":
            return VMTeardownResult("identity_superseded", False)
        return VMTeardownResult("retry_pending", False)

    async def delete_vm(self, job_id: str, purge_disk: bool = True) -> bool:
        """Delete a VM for a job.

        Args:
            job_id: Job UUID.
            purge_disk: False when a recreate is expected (crash recovery, the
                reconciler giving up on a dirty VM) — the controller keeps the
                persistent rootdisk and the Headscale node so the next create
                reattaches the same files. Default True: terminal, everything
                goes. Only honoured by the VM controller (NATS/HTTP); direct
                K8s mode has no standalone rootdisk to keep.

        Returns:
            True if the request was accepted, False otherwise.
        """
        generation = await self._current_provision_generation("job", job_id)
        return await self._delete_vm_with_identity(
            job_id,
            purge_disk=purge_disk,
            provision_generation=generation,
        )

    async def _delete_vm_with_identity(
        self,
        job_id: str,
        *,
        purge_disk: bool,
        provision_generation: str | None,
        expected_vm_uid: str | None = None,
        expected_rootdisk_pvc_uid: str | None = None,
    ) -> bool:
        generation = _provision_generation(provision_generation)
        if nats_bridge.is_available:
            kwargs: dict[str, Any] = {
                "purge_disk": purge_disk,
                "provision_generation": generation,
                "entity_type": "job",
            }
            if expected_vm_uid is not None:
                kwargs["expected_vm_uid"] = expected_vm_uid
            if expected_rootdisk_pvc_uid is not None:
                kwargs["expected_rootdisk_pvc_uid"] = expected_rootdisk_pvc_uid
            return await nats_bridge.request_vm_delete(job_id, **kwargs)

        if self._http_available:
            kwargs = {
                "entity_type": "job",
                "purge_disk": purge_disk,
                "provision_generation": generation,
            }
            if expected_vm_uid is not None:
                kwargs["expected_vm_uid"] = expected_vm_uid
            if expected_rootdisk_pvc_uid is not None:
                kwargs["expected_rootdisk_pvc_uid"] = expected_rootdisk_pvc_uid
            return await self._delete_http(job_id, **kwargs)

        if self._k8s_available:
            self._warn_direct_mode_purges(job_id, purge_disk)
            kwargs = {"provision_generation": generation}
            if expected_vm_uid is not None:
                kwargs["expected_vm_uid"] = expected_vm_uid
            if expected_rootdisk_pvc_uid is not None:
                kwargs["expected_rootdisk_pvc_uid"] = expected_rootdisk_pvc_uid
            return await self._delete_direct(job_id, **kwargs)

        return False

    @staticmethod
    def _warn_direct_mode_purges(entity_id: str, purge_disk: bool) -> None:
        """Direct K8s mode renders the VM template as-is, so the rootdisk is a
        dataVolumeTemplate the VM owns and cascade-deletes. A caller asking to
        keep it will not get what it asked for — say so rather than silently
        destroying the disk it expected to reattach.
        """
        if not purge_disk:
            logger.warning(
                "VM delete for %s requested purge_disk=False, but direct K8s mode "
                "has no persistent rootdisk — the templated disk cascade-deletes "
                "with the VM and its files are lost",
                entity_id,
            )

    async def release_vm(
        self,
        job_id: str,
        ssh_host: Optional[str] = None,
        ssh_port: Optional[int] = None,
    ) -> bool:
        """Snapshot a job VM to S3, then delete it.

        Args:
            job_id: Job UUID.
            ssh_host: SSH host for snapshot (read from DB context if omitted).
            ssh_port: SSH port for snapshot (read from DB context if omitted).

        Returns:
            True if deletion succeeded (snapshot failure is non-fatal).
        """
        # Resolve SSH coordinates from DB if not provided
        if not ssh_host and self._db:
            try:
                job = await self._db.get_job(job_id)
                if job:
                    vm_ctx = _extract_vm_context(job)
                    ssh_host = ssh_host or vm_ctx.get("ssh_host")
                    ssh_port = ssh_port or vm_ctx.get("ssh_port")
            except Exception:
                logger.debug("Could not read VM context for job %s", job_id)

        # Snapshot before delete (best-effort)
        if (
            self._snapshot_service
            and self._snapshot_service.is_available
            and ssh_host
            and ssh_port
        ):
            try:
                # capture_vm_snapshot RETURNS False (it does not raise) when it
                # declines — notably for a VM workspace, whose only address is on
                # the tailnet the orchestrator cannot reach. Ignoring the return
                # made this log a capture that never happened, on every VM
                # release. knowledge-base/knowledge/issues/
                # vm_workspace_snapshot_unreachable_from_orchestrator.md
                captured = await self._snapshot_service.capture_vm_snapshot(
                    job_id=job_id,
                    ssh_host=ssh_host,
                    ssh_port=int(ssh_port),
                    source_type="vm",
                )
                if captured:
                    logger.info(
                        "VM snapshot captured for job %s before release", job_id
                    )
                else:
                    logger.warning(
                        "VM snapshot SKIPPED for job %s (%s:%s) — deleting anyway; "
                        "workspace state not yet pushed to git will be lost. See "
                        "context.snapshot.status for the reason.",
                        job_id,
                        ssh_host,
                        ssh_port,
                    )
            except Exception:
                logger.exception(
                    "VM snapshot failed for job %s — deleting anyway", job_id
                )

        return await self.delete_vm(job_id)

    async def release_thread_vm(
        self,
        thread_id: str,
        ssh_host: Optional[str] = None,
        ssh_port: Optional[int] = None,
    ) -> bool:
        """Snapshot a thread VM to S3, then delete it.

        Args:
            thread_id: Thread UUID.
            ssh_host: SSH host for snapshot (read from DB if omitted).
            ssh_port: SSH port for snapshot (read from DB if omitted).

        Returns:
            True if deletion succeeded (snapshot failure is non-fatal).
        """
        # Resolve SSH coordinates from DB if not provided
        if not ssh_host and self._db:
            try:
                thread = await self._db.get_thread(thread_id)
                if thread:
                    metadata = thread.get("metadata") or {}
                    if isinstance(metadata, str):
                        import json

                        metadata = json.loads(metadata)
                    vm_ctx = metadata.get("vm") or {}
                    ssh_host = ssh_host or vm_ctx.get("ssh_host")
                    ssh_port = ssh_port or vm_ctx.get("ssh_port")
            except Exception:
                logger.debug("Could not read VM context for thread %s", thread_id)

        # Snapshot before delete (best-effort)
        if (
            self._snapshot_service
            and self._snapshot_service.is_available
            and ssh_host
            and ssh_port
        ):
            try:
                # See release_vm: a False return means "declined", not "raised".
                captured = await self._snapshot_service.capture_vm_snapshot(
                    job_id=thread_id,
                    ssh_host=ssh_host,
                    ssh_port=int(ssh_port),
                    source_type="vm",
                    entity_type="threads",
                )
                if captured:
                    logger.info(
                        "VM snapshot captured for thread %s before release", thread_id
                    )
                else:
                    logger.warning(
                        "VM snapshot SKIPPED for thread %s (%s:%s) — deleting "
                        "anyway; workspace state not yet pushed to git will be "
                        "lost. See metadata.snapshot.status for the reason.",
                        thread_id,
                        ssh_host,
                        ssh_port,
                    )
            except Exception:
                logger.exception(
                    "VM snapshot failed for thread %s — deleting anyway", thread_id
                )

        return await self.delete_thread_vm(thread_id)

    async def query_status(
        self,
        job_id: str,
        timeout: float = 5.0,
        entity_type: str = "job",
    ) -> Optional[dict]:
        """Query live VM status.

        NATS mode: request/reply to VM controller.
        HTTP mode: GET /vms/{job_id} on the controller.
        Direct mode: query KubeVirt API.

        Returns:
            Status dict or None if unavailable.
        """
        generation = await self._current_provision_generation(entity_type, job_id)
        result: Optional[dict]
        if nats_bridge.is_available:
            result = await nats_bridge.query_vm_status(
                job_id,
                timeout,
                provision_generation=generation,
            )

        elif self._http_available:
            result = await self._query_http(
                job_id,
                timeout,
                provision_generation=generation,
            )

        elif self._k8s_available:
            result = await self._query_direct(job_id, entity_type=entity_type)

        else:
            return None
        if result is not None:
            if result.get("status") == "not_found":
                return None
            authenticated = result.get("_identity_authenticated") is True
            current = await self._persist_status_identity(entity_type, job_id, result)
            if authenticated and not current:
                return None
            result.pop("_identity_authenticated", None)
        return result

    async def list_vms(
        self, *, include_teardown_identity: bool = False
    ) -> Optional[list]:
        """Enumerate the VMs the backend is actually running.

        Inventory source for the lifecycle VM orphan sweep — the DB-derived
        instance view can't see a VM whose owning row was deleted. Returns a
        list of ``{vm_name, entity_id, created_at, phase}`` dicts, or None
        when no transport can answer (docker pool has no dynamic VMs; an old
        controller without the list op times out / 404s). None means
        "unknown", never "no VMs" — callers must not reap on it.
        """
        if nats_bridge.is_available:
            if include_teardown_identity:
                return await nats_bridge.request_vm_list(include_teardown_identity=True)
            return await nats_bridge.request_vm_list()

        if self._http_available:
            return await self._list_http(
                include_teardown_identity=include_teardown_identity
            )

        if self._k8s_available:
            return await self._list_direct(
                include_teardown_identity=include_teardown_identity
            )

        return None

    async def send_control(self, job_id: str, action: str) -> bool:
        """Send a control command to the management daemon in a VM.

        Only works via NATS (the daemon listens on NATS subjects).
        Returns False if NATS is unavailable.

        Args:
            job_id: Job UUID.
            action: One of "freeze", "resume", "terminate".
        """
        if nats_bridge.is_available:
            return await nats_bridge.send_control(job_id, action)
        return False

    # =========================================================================
    # Direct K8s backend (same-cluster)
    # =========================================================================

    async def _rootdisk_pvc_uid(
        self,
        *,
        owner_id: str,
        owner_kind: str,
        wait: bool,
    ) -> str | None:
        """Read the exact admitted root PVC identity for direct K8s mode."""

        _known, uid = await self._rootdisk_pvc_probe(
            owner_id=owner_id,
            owner_kind=owner_kind,
            wait=wait,
        )
        return uid

    async def _rootdisk_pvc_probe(
        self,
        *,
        owner_id: str,
        owner_kind: str,
        wait: bool,
    ) -> tuple[bool, str | None]:
        """Return ``(known, uid)`` so exact absence is not transport loss."""

        if self._core_k8s is None:
            logger.warning(
                "Rootdisk PVC identity unavailable for %s: CoreV1Api is not initialized",
                owner_id,
            )
            return False, None
        name = f"agent-vm-{owner_id}-rootdisk"
        attempts = max(1, VM_ROOTDISK_PVC_UID_ATTEMPTS if wait else 1)
        exact_absence = False
        for attempt in range(attempts):
            try:
                pvc = await asyncio.to_thread(
                    self._core_k8s.read_namespaced_persistent_volume_claim,
                    name=name,
                    namespace=self._vm_namespace,
                )
            except Exception as exc:
                if getattr(exc, "status", None) != 404:
                    logger.warning(
                        "Rootdisk PVC identity read failed for %s: %s", name, exc
                    )
                    return False, None
                exact_absence = True
            else:
                uid = _admitted_pvc_uid(
                    pvc,
                    expected_name=name,
                    expected_owner_id=owner_id,
                    expected_owner_kind=owner_kind,
                )
                if uid is not None:
                    return True, uid
                return False, None
            if attempt + 1 < attempts and VM_ROOTDISK_PVC_UID_RETRY_SECONDS > 0:
                await asyncio.sleep(VM_ROOTDISK_PVC_UID_RETRY_SECONDS)
        if exact_absence:
            return True, None
        logger.warning(
            "Rootdisk PVC %s was not admitted with the expected immutable identity; "
            "storage attribution will remain unknown",
            name,
        )
        return False, None

    async def _create_direct(
        self,
        job_id: str,
        agent_config: str,
        vm_image: Optional[str],
        cpu_cores: int,
        memory: str,
        description: str,
        provision_generation: str,
    ) -> bool:
        """Create a VM via direct Kubernetes API call."""
        job_config = {
            "job_id": job_id,
            "entity_type": "job",
            "agent_config": agent_config,
            "vm_image": vm_image,
            "cpu_cores": cpu_cores,
            "memory": memory,
            "description": description,
            "provision_generation": provision_generation,
            "nats_url": os.environ.get("NATS_URL", ""),
        }

        try:
            manifest = self._render_template(job_config)
            vm_name = manifest["metadata"]["name"]

            # K8s client is synchronous — run in thread pool
            admitted_vm = await asyncio.to_thread(
                self._k8s.create_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
                body=manifest,
            )
            vm_uid = _admitted_vm_uid(admitted_vm, expected_name=vm_name)
            admitted_generation = _admitted_provision_generation(admitted_vm)
            if vm_uid is None or admitted_generation != provision_generation:
                admitted_vm = await asyncio.to_thread(
                    self._k8s.get_namespaced_custom_object,
                    group=KUBEVIRT_GROUP,
                    version=KUBEVIRT_VERSION,
                    namespace=self._vm_namespace,
                    plural=KUBEVIRT_PLURAL,
                    name=vm_name,
                )
                vm_uid = _admitted_vm_uid(admitted_vm, expected_name=vm_name)
                admitted_generation = _admitted_provision_generation(admitted_vm)
            if vm_uid is None:
                raise RuntimeError("Kubernetes admitted VM response lacks metadata.uid")
            if admitted_generation != provision_generation:
                raise RuntimeError(
                    "Kubernetes admitted VM response has another provision generation"
                )

            rootdisk_pvc_uid = await self._rootdisk_pvc_uid(
                owner_id=job_id,
                owner_kind="job",
                wait=True,
            )

            logger.info("VM created (direct): %s (job %s)", vm_name, job_id)
            updates = {
                "status": "created",
                "vm_name": vm_name,
                "vm_uid": vm_uid,
                "namespace": self._vm_namespace,
                "provisioned_by": "direct",
                "identity_authenticated": True,
                "identity_provision_generation": provision_generation,
            }
            if rootdisk_pvc_uid is not None:
                updates["rootdisk_pvc_uid"] = rootdisk_pvc_uid
            await self._set_vm_context_if_generation(
                job_id,
                provision_generation,
                updates,
            )
            return True
        except Exception as e:
            logger.error("Failed to create VM for job %s: %s", job_id, e)
            await self._set_vm_context_if_generation(
                job_id,
                provision_generation,
                {
                    "status": "failed",
                    "error": str(e),
                    "provisioned_by": "direct",
                },
            )
            return False

    async def _delete_direct(
        self,
        job_id: str,
        *,
        provision_generation: str | None = None,
        expected_vm_uid: str | None = None,
        expected_rootdisk_pvc_uid: str | None = None,
    ) -> bool:
        """Delete a VM via direct Kubernetes API call."""
        vm_name = f"agent-vm-{job_id}"

        generation = _provision_generation(provision_generation)
        if generation is None:
            logger.error(
                "Refusing direct delete for %s without a current provision generation",
                job_id,
            )
            return False

        try:
            current_vm = await asyncio.to_thread(
                self._k8s.get_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
                name=vm_name,
            )
            if _admitted_provision_generation(current_vm) != generation:
                logger.error(
                    "Refusing direct delete for %s: provision generation changed",
                    job_id,
                )
                return False
            metadata = (
                current_vm.get("metadata") if isinstance(current_vm, Mapping) else None
            )
            vm_uid = (
                _safe_vm_uid(metadata.get("uid"))
                if isinstance(metadata, Mapping)
                else None
            )
            if vm_uid is None:
                logger.error(
                    "Refusing direct delete for %s: admitted VM UID is unavailable",
                    job_id,
                )
                return False
            if expected_vm_uid is not None and vm_uid != expected_vm_uid:
                logger.info(
                    "Captured VM UID superseded for %s; preserving replacement",
                    job_id,
                )
                return False
            if expected_rootdisk_pvc_uid is not None:
                current_rootdisk_uid = await self._rootdisk_pvc_uid(
                    owner_id=job_id,
                    owner_kind="job",
                    wait=False,
                )
                if current_rootdisk_uid != expected_rootdisk_pvc_uid:
                    logger.info(
                        "Captured rootdisk UID superseded for %s; preserving replacement",
                        job_id,
                    )
                    return False
            await asyncio.to_thread(
                self._k8s.delete_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
                name=vm_name,
                body={
                    "apiVersion": "v1",
                    "kind": "DeleteOptions",
                    "preconditions": {"uid": vm_uid},
                },
            )

            logger.info("VM deleted (direct): %s (job %s)", vm_name, job_id)
            await self._set_vm_context_if_generation(
                job_id, generation, {"status": "deleted"}
            )
            return True
        except Exception as e:
            if getattr(e, "status", None) == 404:
                logger.debug("VM already deleted: %s (job %s)", vm_name, job_id)
                await self._set_vm_context_if_generation(
                    job_id, generation, {"status": "deleted"}
                )
                return True
            logger.error("Failed to delete VM for job %s: %s", job_id, e)
            return False

    async def _query_direct(
        self,
        job_id: str,
        *,
        entity_type: str = "job",
        absent_generation: str | None = None,
    ) -> Optional[dict]:
        """Query VM status via direct Kubernetes API call."""
        vm_name = f"agent-vm-{job_id}"

        try:
            vm = await asyncio.to_thread(
                self._k8s.get_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
                name=vm_name,
            )

            status = vm.get("status", {})
            conditions = status.get("conditions", [])
            ready = any(
                c.get("type") == "Ready" and c.get("status") == "True"
                for c in conditions
            )

            result = {
                "job_id": job_id,
                "vm_name": vm_name,
                "namespace": self._vm_namespace,
                "ready": ready,
                "phase": status.get("printableStatus", "Unknown"),
                "created": status.get("created", False),
            }
            if (vm_uid := _admitted_vm_uid(vm, expected_name=vm_name)) is not None:
                result["vm_uid"] = vm_uid
            generation = _admitted_provision_generation(vm)
            if generation is not None:
                result["provision_generation"] = generation
            if absent_generation is not None:
                rootdisk_known, rootdisk_pvc_uid = await self._rootdisk_pvc_probe(
                    owner_id=job_id,
                    owner_kind=entity_type,
                    wait=False,
                )
                result["rootdisk_identity_known"] = rootdisk_known
            else:
                # The ordinary lifecycle/status path keeps its historical
                # result shape.  Absence authority is opt-in for teardown.
                rootdisk_pvc_uid = await self._rootdisk_pvc_uid(
                    owner_id=job_id,
                    owner_kind=entity_type,
                    wait=False,
                )
            if rootdisk_pvc_uid is not None:
                result["rootdisk_pvc_uid"] = rootdisk_pvc_uid
            if generation is not None and "vm_uid" in result:
                result["_identity_authenticated"] = True
            return result
        except Exception as e:
            if getattr(e, "status", None) == 404 and absent_generation is not None:
                rootdisk_known, rootdisk_pvc_uid = await self._rootdisk_pvc_probe(
                    owner_id=job_id,
                    owner_kind=entity_type,
                    wait=False,
                )
                return {
                    "job_id": job_id,
                    "status": "not_found",
                    "provision_generation": absent_generation,
                    "rootdisk_identity_known": rootdisk_known,
                    **(
                        {"rootdisk_pvc_uid": rootdisk_pvc_uid}
                        if rootdisk_pvc_uid is not None
                        else {}
                    ),
                    "_identity_authenticated": True,
                }
            logger.debug("VM status query failed for job %s: %s", job_id, e)
            return None

    # =========================================================================
    # HTTP controller backend (same-cluster, controller-mediated)
    #
    # The controller still owns KubeVirt RBAC and the VM template; this
    # transport just swaps NATS for HTTP. Status updates that NATS pushed
    # asynchronously now arrive synchronously in the response body, so
    # context updates happen here in the orchestrator instead of via the
    # vm.lifecycle.status subscription.
    #
    # Caveat: in-VM daemon events (register/heartbeat/freeze/resume) are
    # NOT carried by this transport. Same-cluster deployments that need
    # those still need NATS (or a future HTTP webhook from the daemon).
    # =========================================================================

    async def _create_http(
        self,
        job_id: str,
        agent_config: str,
        vm_image: Optional[str],
        cpu_cores: int,
        memory: str,
        description: str,
        entity_type: str = "job",
        set_provisioning: bool = True,
        provision_generation: str | None = None,
    ) -> bool:
        """Create a VM by POSTing to the co-located VM controller.

        ``set_provisioning=False`` marks a golden-poll re-issue: skip the
        interim 'provisioning' context write so the status stays
        ``waiting_golden`` between polls (the response merge below still
        records whatever the controller answered).
        """
        if self._http_client is None:
            return False

        payload: dict[str, Any] = {
            "job_id": job_id,
            "entity_type": entity_type,
            "agent_config": agent_config,
            "cpu_cores": cpu_cores,
            "memory": memory,
            "description": description,
            "nats_url": "",  # No NATS in same-cluster mode
        }
        generation = _provision_generation(provision_generation)
        if self._lifecycle_hmac_secret is not None and generation is None:
            logger.error(
                "Refusing authenticated HTTP VM create for %s %s without a "
                "current provision generation",
                entity_type,
                job_id,
            )
            return False
        if generation is not None:
            payload["provision_generation"] = generation
        if vm_image:
            payload["vm_image"] = vm_image
        payload = sign_payload(
            payload,
            direction="request",
            operation="create",
            secret=self._lifecycle_hmac_secret,
        )
        request_auth = payload.get(AUTH_FIELD)
        request_id = (
            request_auth.get("request_id")
            if isinstance(request_auth, Mapping)
            else None
        )

        try:
            if set_provisioning:
                if generation is not None:
                    await self._set_context_if_generation(
                        entity_type,
                        job_id,
                        generation,
                        {"status": "provisioning"},
                    )
                else:
                    await self._set_context(
                        entity_type, job_id, {"status": "provisioning"}
                    )
            resp = await self._http_client.post("/vms", json=payload)
            data = resp.json()
            if not isinstance(data, Mapping) or not verify_payload(
                data,
                direction="response",
                operation="create",
                secret=self._lifecycle_hmac_secret,
                expected_correlation_id=request_id,
            ):
                raise RuntimeError(
                    "VM controller create response authentication failed"
                )
            resp.raise_for_status()
            data = unsigned_payload(data)

            updates = {
                "status": data.get("status", "created"),
                "vm_name": data.get("vm_name"),
                "namespace": data.get("namespace"),
                "provisioned_by": "http",
            }
            # New controllers return the immutable admitted VM UID. During a
            # rolling upgrade an older controller may omit it; the fresh
            # context reset leaves vm_uid=None so metering classifies that VM
            # as legacy-unknown instead of trusting its reusable name.
            # Deferred-create responses carry telemetry instead of a VM name
            # (golden import progress, or why the mesh VPN is unreachable);
            # surface it for the dispatcher's poll logging and park message.
            for key in (
                "golden",
                "golden_phase",
                "golden_progress",
                "headscale_error",
            ):
                if data.get(key) is not None:
                    updates[key] = data[key]
            response_generation = _provision_generation(
                data.get("provision_generation")
            )
            identity_updates: dict[str, Any] = {}
            if (
                self._lifecycle_hmac_secret is not None
                and response_generation is not None
                and response_generation == generation
            ):
                if (vm_uid := _safe_vm_uid(data.get("vm_uid"))) is not None:
                    identity_updates["vm_uid"] = vm_uid
                if (
                    rootdisk_pvc_uid := _safe_vm_uid(data.get("rootdisk_pvc_uid"))
                ) is not None:
                    identity_updates["rootdisk_pvc_uid"] = rootdisk_pvc_uid
                if identity_updates:
                    identity_updates.update(
                        {
                            "identity_authenticated": True,
                            "identity_provision_generation": response_generation,
                        }
                    )
            if response_generation and response_generation == generation:
                merged = await self._set_context_if_generation(
                    entity_type,
                    job_id,
                    response_generation,
                    {**updates, **identity_updates},
                )
                if not merged:
                    if self._lifecycle_hmac_secret is not None:
                        logger.warning(
                            "Ignoring stale authenticated HTTP create response for "
                            "%s %s",
                            entity_type,
                            job_id,
                        )
                    else:
                        await self._set_context(entity_type, job_id, updates)
            else:
                if self._lifecycle_hmac_secret is not None:
                    logger.warning(
                        "Ignoring authenticated HTTP create response with a stale or "
                        "missing provision generation for %s %s",
                        entity_type,
                        job_id,
                    )
                else:
                    await self._set_context(entity_type, job_id, updates)
            if data.get("status") == "waiting_golden":
                logger.info(
                    "VM create deferred (http): golden %s importing (%s %s)",
                    data.get("golden"),
                    entity_type,
                    job_id,
                )
            elif data.get("status") == "waiting_headscale":
                logger.info(
                    "VM create deferred (http): Headscale unavailable (%s) (%s %s)",
                    data.get("headscale_error"),
                    entity_type,
                    job_id,
                )
            else:
                logger.info(
                    "VM created (http): %s (%s %s)",
                    data.get("vm_name"),
                    entity_type,
                    job_id,
                )
            return True
        except httpx.HTTPStatusError as e:
            error = _extract_http_error(e.response)
            logger.error(
                "VM controller rejected create for %s %s: %s",
                entity_type,
                job_id,
                error,
            )
            failure = {
                "status": "failed",
                "error": error,
                "provisioned_by": "http",
            }
            if generation is not None:
                await self._set_context_if_generation(
                    entity_type, job_id, generation, failure
                )
            else:
                await self._set_context(entity_type, job_id, failure)
            return False
        except Exception as e:
            logger.error("HTTP create failed for %s %s: %s", entity_type, job_id, e)
            failure = {
                "status": "failed",
                "error": str(e),
                "provisioned_by": "http",
            }
            if generation is not None:
                await self._set_context_if_generation(
                    entity_type, job_id, generation, failure
                )
            else:
                await self._set_context(entity_type, job_id, failure)
            return False

    async def _delete_http(
        self,
        job_id: str,
        entity_type: str = "job",
        purge_disk: bool = True,
        provision_generation: str | None = None,
        expected_vm_uid: str | None = None,
        expected_rootdisk_pvc_uid: str | None = None,
    ) -> bool:
        """Delete a VM by sending DELETE to the co-located VM controller."""
        if self._http_client is None:
            return False

        generation = _provision_generation(provision_generation)
        if self._lifecycle_hmac_secret is not None and generation is None:
            logger.error(
                "Refusing authenticated HTTP VM delete for %s without a current "
                "provision generation",
                job_id,
            )
            return False
        signed_payload = {
            "job_id": job_id,
            "purge_disk": purge_disk,
            "provision_generation": generation,
        }
        if expected_vm_uid is not None:
            signed_payload["expected_vm_uid"] = expected_vm_uid
        if expected_rootdisk_pvc_uid is not None:
            signed_payload["expected_rootdisk_pvc_uid"] = expected_rootdisk_pvc_uid
        params: dict[str, str] = {}
        if not purge_disk:
            params["purge_disk"] = "false"
        if generation is not None:
            params["provision_generation"] = generation
        if expected_vm_uid is not None:
            params["expected_vm_uid"] = expected_vm_uid
        if expected_rootdisk_pvc_uid is not None:
            params["expected_rootdisk_pvc_uid"] = expected_rootdisk_pvc_uid
        params.update(
            _http_lifecycle_query(
                signed_payload,
                operation="delete",
                secret=self._lifecycle_hmac_secret,
            )
        )
        request_id = params.get("lifecycle_auth_request_id")
        try:
            resp = await self._http_client.delete(f"/vms/{job_id}", params=params)
            data: Mapping[str, Any] | None = None
            if self._lifecycle_hmac_secret is not None or resp.status_code != 404:
                candidate = resp.json()
                if not isinstance(candidate, Mapping) or not verify_payload(
                    candidate,
                    direction="response",
                    operation="delete",
                    secret=self._lifecycle_hmac_secret,
                    expected_correlation_id=request_id,
                ):
                    raise RuntimeError(
                        "VM controller delete response authentication failed"
                    )
                data = unsigned_payload(candidate)
            if resp.status_code != 404:
                resp.raise_for_status()
            if self._lifecycle_hmac_secret is not None:
                response_generation = _provision_generation(
                    data.get("provision_generation") if data else None
                )
                if response_generation != generation:
                    raise RuntimeError(
                        "VM controller delete response generation mismatch"
                    )
            if generation is not None:
                await self._set_context_if_generation(
                    entity_type, job_id, generation, {"status": "deleted"}
                )
            else:
                await self._set_context(entity_type, job_id, {"status": "deleted"})
            logger.info("VM deleted (http): %s %s", entity_type, job_id)
            return True
        except httpx.HTTPStatusError as e:
            error = _extract_http_error(e.response)
            logger.error(
                "VM controller rejected delete for %s %s: %s",
                entity_type,
                job_id,
                error,
            )
            return False
        except Exception as e:
            logger.error("HTTP delete failed for %s %s: %s", entity_type, job_id, e)
            return False

    async def _query_http(
        self,
        job_id: str,
        timeout: float = 5.0,
        provision_generation: str | None = None,
        *,
        exact_absence: bool = False,
    ) -> Optional[dict]:
        """Query VM status via the co-located VM controller."""
        if self._http_client is None:
            return None

        generation = _provision_generation(provision_generation)
        if self._lifecycle_hmac_secret is not None and generation is None:
            return None
        signed_payload = {
            "job_id": job_id,
            "provision_generation": generation,
        }
        params: dict[str, str] = {}
        if generation is not None:
            params["provision_generation"] = generation
        if exact_absence:
            signed_payload["exact_absence"] = True
            params["exact_absence"] = "true"
        params.update(
            _http_lifecycle_query(
                signed_payload,
                operation="status",
                secret=self._lifecycle_hmac_secret,
            )
        )
        request_id = params.get("lifecycle_auth_request_id")
        try:
            resp = await self._http_client.get(
                f"/vms/{job_id}", params=params, timeout=timeout
            )
            data = resp.json()
            if not isinstance(data, Mapping) or not verify_payload(
                data,
                direction="response",
                operation="status",
                secret=self._lifecycle_hmac_secret,
                expected_correlation_id=request_id,
            ):
                return None
            result = unsigned_payload(data)
            if (
                self._lifecycle_hmac_secret is not None
                and _provision_generation(result.get("provision_generation"))
                != generation
            ):
                return None
            if resp.status_code == 404:
                return None
            resp.raise_for_status()
            if self._lifecycle_hmac_secret is not None:
                result["_identity_authenticated"] = True
            return result
        except Exception as e:
            logger.debug("HTTP status query failed for job %s: %s", job_id, e)
            return None

    async def _list_http(
        self, *, include_teardown_identity: bool = False
    ) -> Optional[list]:
        """List managed VMs via the co-located VM controller.

        A 404 means the controller predates the list op — unknown, not empty.
        """
        if self._http_client is None:
            return None

        try:
            signed_payload = {
                **(
                    {"include_teardown_identity": True}
                    if include_teardown_identity
                    else {}
                )
            }
            params = _http_lifecycle_query(
                signed_payload, operation="list", secret=self._lifecycle_hmac_secret
            )
            if include_teardown_identity:
                params["include_teardown_identity"] = "true"
            resp = await self._http_client.get(
                "/vms",
                params=params,
            )
            if resp.status_code == 404:
                return None
            resp.raise_for_status()
            data = resp.json()
            if not isinstance(data, Mapping) or not verify_payload(
                data,
                direction="response",
                operation="list",
                secret=self._lifecycle_hmac_secret,
                expected_correlation_id=params.get("lifecycle_auth_request_id"),
            ):
                return None
            vms = unsigned_payload(data).get("vms")
            return vms if isinstance(vms, list) else None
        except Exception as e:
            logger.debug("HTTP VM list failed: %s", e)
            return None

    async def _list_direct(
        self, *, include_teardown_identity: bool = False
    ) -> Optional[list]:
        """List managed VMs via direct Kubernetes API call.

        Mirrors the controller's ``_do_list``: agent VMs only, golden
        DataVolume names excluded as defense-in-depth.
        """
        try:
            vms = await asyncio.to_thread(
                self._k8s.list_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
            )
        except Exception as e:
            logger.debug("Direct VM list failed: %s", e)
            return None

        out = []
        for item in vms.get("items", []):
            meta = item.get("metadata", {})
            name = meta.get("name", "")
            if not name.startswith("agent-vm-") or name.startswith("agent-vm-golden-"):
                continue
            entity_id = name[len("agent-vm-") :]
            inventory = {
                "vm_name": name,
                "entity_id": entity_id,
                "created_at": meta.get("creationTimestamp"),
                "phase": item.get("status", {}).get("printableStatus", "Unknown"),
            }
            if include_teardown_identity:
                generation = _admitted_provision_generation(item)
                vm_uid = _admitted_vm_uid(item, expected_name=name)
                rootdisk_uid = await self._rootdisk_pvc_uid(
                    owner_id=entity_id,
                    owner_kind=None,
                    wait=False,
                )
                if generation is not None:
                    inventory["provision_generation"] = generation
                if vm_uid is not None:
                    inventory["vm_uid"] = vm_uid
                if rootdisk_uid is not None:
                    inventory["rootdisk_pvc_uid"] = rootdisk_uid
            out.append(inventory)
        return out

    async def _set_context(
        self, entity_type: str, entity_id: str, updates: dict
    ) -> None:
        """Route context updates to the right table based on entity type."""
        if entity_type == "thread":
            await self._set_thread_vm_context(entity_id, updates)
        else:
            await self._set_vm_context(entity_id, updates)

    # =========================================================================
    # Helpers
    # =========================================================================

    @staticmethod
    def _fresh_provision_ctx() -> dict:
        """Reap-counter/endpoint reset + provision timestamp for a new VM.

        Merged into context.vm at the start of every (re)provision so the new
        incarnation does not inherit the previous one's snapshot_attempts (which
        would make the lifecycle reaper's attempts_exhausted instantly true), a
        dead ssh_host, or stale SSH-readiness probe identity. ``provisioned_at``
        (epoch seconds) anchors the dispatcher's provisioning-timeout escalation.
        """
        return {
            "snapshot_attempts": 0,
            "ssh_host": None,
            "ssh_port": None,
            "ssh_registration_id": None,
            "registered_at": None,
            "ssh_verified_at": None,
            "ssh_probe_attempts": 0,
            "ssh_probe_error": None,
            "ssh_probe_failed_at": None,
            # Never let a previous VM incarnation's UID authenticate the next
            # one between create dispatch and the admitted controller result.
            "vm_uid": None,
            # A PVC name is reusable.  Only the newly admitted immutable UID
            # may authenticate this incarnation's rootdisk for metering.
            "rootdisk_pvc_uid": None,
            "identity_authenticated": False,
            "identity_provision_generation": None,
            # Opaque incarnation nonce. Controller identities are merged only
            # through a DB-side compare-and-merge against this exact value.
            "provision_generation": str(uuid4()),
            # Slice 1 does not trust a guest self-reported VM host key. Keep
            # Canvas closed until the VM provisioner can attest the key.
            CANVAS_WORKSPACE_GENERATION_KEY: None,
            # Golden-wait anchor from a previous incarnation must not cap this
            # provision's patience for a cold golden import (dispatcher stamps
            # it again on the first waiting_golden it sees). Same for the
            # Headscale-wait anchor.
            "golden_wait_started_at": None,
            "headscale_wait_started_at": None,
            # Same for the teardown anchor: a stale one would make this
            # incarnation read as instantly-stuck the moment it enters
            # 'deleting', and the dispatcher would recycle it on sight.
            "deleting_started_at": None,
            "headscale_error": None,
            "provisioned_at": time.time(),
        }

    async def _set_vm_context(self, job_id: str, updates: dict) -> None:
        """Atomically merge updates into the job's context.vm key."""
        if not self._db:
            return

        try:
            await self._db.merge_vm_context(job_id, updates)
        except Exception:
            logger.exception("Failed to update VM context for job %s", job_id)

    # =========================================================================
    # Thread VM support (persistent agent sessions)
    # =========================================================================

    async def create_thread_vm(
        self,
        thread_id: str,
        agent_config: str = "worker_base",
        vm_image: Optional[str] = None,
        cpu_cores: int = 8,
        memory: str = "16Gi",
        description: str = "",
    ) -> bool:
        """Create a VM for a persistent thread.

        Mirrors create_vm() but routes context to threads.metadata.vm
        and uses entity_type="thread" for NATS bridge routing.

        Returns:
            True if the request was accepted, False otherwise.
        """
        # See create_vm: reset the reap counter / stale endpoint and stamp
        # provisioned_at before backend dispatch (thread-scoped context).
        fresh_context = self._fresh_provision_ctx()
        generation = fresh_context["provision_generation"]
        await self._set_thread_vm_context(thread_id, fresh_context)
        if nats_bridge.is_available:
            return await nats_bridge.request_vm_create(
                job_id=thread_id,
                agent_config=agent_config,
                vm_image=vm_image,
                cpu_cores=cpu_cores,
                memory=memory,
                description=description,
                entity_type="thread",
                provision_generation=generation,
            )

        if self._http_available:
            return await self._create_http(
                job_id=thread_id,
                agent_config=agent_config,
                vm_image=vm_image,
                cpu_cores=cpu_cores,
                memory=memory,
                description=description,
                entity_type="thread",
                provision_generation=generation,
            )

        if self._k8s_available:
            return await self._create_thread_vm_direct(
                thread_id=thread_id,
                agent_config=agent_config,
                vm_image=vm_image,
                cpu_cores=cpu_cores,
                memory=memory,
                description=description,
                provision_generation=generation,
            )

        return False

    async def delete_thread_vm(self, thread_id: str, purge_disk: bool = True) -> bool:
        """Delete a VM for a persistent thread.

        Args:
            thread_id: Thread UUID.
            purge_disk: False when the session expects to come back (suspend) —
                see ``delete_vm``.

        Returns:
            True if the request was accepted, False otherwise.
        """
        generation = await self._current_provision_generation("thread", thread_id)
        if nats_bridge.is_available:
            return await nats_bridge.request_vm_delete(
                thread_id,
                purge_disk=purge_disk,
                provision_generation=generation,
                entity_type="thread",
            )

        if self._http_available:
            return await self._delete_http(
                thread_id,
                entity_type="thread",
                purge_disk=purge_disk,
                provision_generation=generation,
            )

        if self._k8s_available:
            self._warn_direct_mode_purges(thread_id, purge_disk)
            return await self._delete_thread_vm_direct(
                thread_id, provision_generation=generation
            )

        return False

    async def _create_thread_vm_direct(
        self,
        thread_id: str,
        agent_config: str,
        vm_image: Optional[str],
        cpu_cores: int,
        memory: str,
        description: str,
        provision_generation: str,
    ) -> bool:
        """Create a thread VM via direct Kubernetes API call."""
        job_config = {
            "job_id": thread_id,  # Template uses ${JOB_ID}
            "entity_type": "thread",
            "agent_config": agent_config,
            "vm_image": vm_image,
            "cpu_cores": cpu_cores,
            "memory": memory,
            "description": description,
            "provision_generation": provision_generation,
            "nats_url": os.environ.get("NATS_URL", ""),
        }

        try:
            manifest = self._render_template(job_config)
            vm_name = manifest["metadata"]["name"]

            admitted_vm = await asyncio.to_thread(
                self._k8s.create_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
                body=manifest,
            )
            vm_uid = _admitted_vm_uid(admitted_vm, expected_name=vm_name)
            admitted_generation = _admitted_provision_generation(admitted_vm)
            if vm_uid is None or admitted_generation != provision_generation:
                admitted_vm = await asyncio.to_thread(
                    self._k8s.get_namespaced_custom_object,
                    group=KUBEVIRT_GROUP,
                    version=KUBEVIRT_VERSION,
                    namespace=self._vm_namespace,
                    plural=KUBEVIRT_PLURAL,
                    name=vm_name,
                )
                vm_uid = _admitted_vm_uid(admitted_vm, expected_name=vm_name)
                admitted_generation = _admitted_provision_generation(admitted_vm)
            if vm_uid is None:
                raise RuntimeError("Kubernetes admitted VM response lacks metadata.uid")
            if admitted_generation != provision_generation:
                raise RuntimeError(
                    "Kubernetes admitted VM response has another provision generation"
                )

            rootdisk_pvc_uid = await self._rootdisk_pvc_uid(
                owner_id=thread_id,
                owner_kind="thread",
                wait=True,
            )

            logger.info(
                "Thread VM created (direct): %s (thread %s)", vm_name, thread_id
            )
            updates = {
                "status": "created",
                "vm_name": vm_name,
                "vm_uid": vm_uid,
                "namespace": self._vm_namespace,
                "provisioned_by": "direct",
                "identity_authenticated": True,
                "identity_provision_generation": provision_generation,
            }
            if rootdisk_pvc_uid is not None:
                updates["rootdisk_pvc_uid"] = rootdisk_pvc_uid
            await self._set_thread_vm_context_if_generation(
                thread_id,
                provision_generation,
                updates,
            )
            return True
        except Exception as e:
            logger.error("Failed to create thread VM for %s: %s", thread_id, e)
            await self._set_thread_vm_context_if_generation(
                thread_id,
                provision_generation,
                {
                    "status": "failed",
                    "error": str(e),
                    "provisioned_by": "direct",
                },
            )
            return False

    async def _delete_thread_vm_direct(
        self, thread_id: str, *, provision_generation: str | None = None
    ) -> bool:
        """Delete a thread VM via direct Kubernetes API call."""
        vm_name = f"agent-vm-{thread_id}"

        generation = _provision_generation(provision_generation)
        if generation is None:
            logger.error(
                "Refusing direct thread delete for %s without a current provision "
                "generation",
                thread_id,
            )
            return False

        try:
            current_vm = await asyncio.to_thread(
                self._k8s.get_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
                name=vm_name,
            )
            if _admitted_provision_generation(current_vm) != generation:
                logger.error(
                    "Refusing direct thread delete for %s: provision generation "
                    "changed",
                    thread_id,
                )
                return False
            metadata = (
                current_vm.get("metadata") if isinstance(current_vm, Mapping) else None
            )
            vm_uid = (
                _safe_vm_uid(metadata.get("uid"))
                if isinstance(metadata, Mapping)
                else None
            )
            if vm_uid is None:
                logger.error(
                    "Refusing direct thread delete for %s: admitted VM UID is "
                    "unavailable",
                    thread_id,
                )
                return False
            await asyncio.to_thread(
                self._k8s.delete_namespaced_custom_object,
                group=KUBEVIRT_GROUP,
                version=KUBEVIRT_VERSION,
                namespace=self._vm_namespace,
                plural=KUBEVIRT_PLURAL,
                name=vm_name,
                body={
                    "apiVersion": "v1",
                    "kind": "DeleteOptions",
                    "preconditions": {"uid": vm_uid},
                },
            )

            logger.info(
                "Thread VM deleted (direct): %s (thread %s)", vm_name, thread_id
            )
            await self._set_thread_vm_context_if_generation(
                thread_id, generation, {"status": "deleted"}
            )
            return True
        except Exception as e:
            if getattr(e, "status", None) == 404:
                logger.debug(
                    "Thread VM already deleted: %s (thread %s)",
                    vm_name,
                    thread_id,
                )
                await self._set_thread_vm_context_if_generation(
                    thread_id, generation, {"status": "deleted"}
                )
                return True
            logger.error("Failed to delete thread VM for %s: %s", thread_id, e)
            return False

    async def _set_thread_vm_context(self, thread_id: str, updates: dict) -> None:
        """Atomically merge updates into thread's metadata.vm key."""
        if not self._db:
            return

        try:
            await self._db.merge_thread_vm_context(thread_id, updates)
        except Exception:
            logger.exception("Failed to update thread VM context for %s", thread_id)

    async def _set_thread_vm_context_if_generation(
        self, thread_id: str, generation: str, updates: dict
    ) -> bool:
        if not self._db:
            return False
        try:
            return bool(
                await self._db.merge_thread_vm_context_if_provision_generation(
                    thread_id, generation, updates
                )
            )
        except Exception:
            logger.exception(
                "Failed to update generation-guarded thread VM context for %s",
                thread_id,
            )
            return False


def _extract_http_error(response: httpx.Response) -> str:
    """Pull a useful error message out of a controller HTTP error response."""
    try:
        data = response.json()
        if isinstance(data, dict) and data.get("error"):
            return str(data["error"])
    except Exception:
        pass
    text = (response.text or "").strip()
    return text or f"HTTP {response.status_code}"


# Module-level singleton
vm_provisioner = VMProvisioner()
