#!/usr/bin/env python3
"""Generate committed job-surface mirrors from the Python descriptors."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.shared.orch_surface.jobs import JOB_DESCRIPTORS  # noqa: E402

TS_PATH = ROOT / "cockpit/src/app/core/tools/job-surface.generated.ts"
CATALOGUE_PATH = ROOT / "knowledge-base/knowledge/generated/job_tool_catalogue.md"

GROUP_PRESENTATION = {
    "job_control": {
        "label": "Job Control",
        "icon": "play_circle",
        "description": "Create, steer, pause, resume, approve, and cancel SRW jobs",
    },
    "job_inspection": {
        "label": "Job Inspection",
        "icon": "manage_search",
        "description": "Inspect SRW job status and the currently granted supervision data",
    },
}


def _typescript() -> str:
    rows = []
    for item in JOB_DESCRIPTORS:
        callers = ", ".join(json.dumps(value) for value in sorted(item.caller_defaults))
        grant = json.dumps(item.grant) if item.grant else "null"
        rows.append(
            "  {"
            f"name: {json.dumps(item.name)}, group: {json.dumps(item.group)}, "
            f"plane: {json.dumps(item.plane)}, callerDefaults: [{callers}], "
            f"grant: {grant}"
            "},"
        )
    groups = []
    for key in ("job_control", "job_inspection"):
        presentation = GROUP_PRESENTATION[key]
        groups.append(
            "  {"
            f"key: {json.dumps(key)}, label: {json.dumps(presentation['label'])}, "
            f"icon: {json.dumps(presentation['icon'])}, "
            f"description: {json.dumps(presentation['description'])}"
            "},"
        )
    return (
        "/* Generated by scripts/generate-job-surface.py; do not edit. */\n\n"
        "export type JobToolGroup = 'job_control' | 'job_inspection';\n"
        "export type JobToolPlane =\n"
        "  | 'job_control'\n"
        "  | 'job_observability'\n"
        "  | 'job_evidence'\n"
        "  | 'job_workspace';\n"
        "export type JobToolCaller = 'mcp' | 'officer' | 'session';\n\n"
        "export interface GeneratedJobToolDescriptor {\n"
        "  readonly name: string;\n"
        "  readonly group: JobToolGroup;\n"
        "  readonly plane: JobToolPlane;\n"
        "  readonly callerDefaults: readonly JobToolCaller[];\n"
        "  readonly grant: 'explicit' | null;\n"
        "}\n\n"
        "export interface GeneratedJobToolGroupMeta {\n"
        "  readonly key: JobToolGroup;\n"
        "  readonly label: string;\n"
        "  readonly icon: string;\n"
        "  readonly description: string;\n"
        "}\n\n"
        "export const JOB_TOOL_DESCRIPTORS: readonly GeneratedJobToolDescriptor[] = [\n"
        + "\n".join(rows)
        + "\n] as const;\n\n"
        "export const JOB_TOOL_GROUP_CATEGORIES: readonly GeneratedJobToolGroupMeta[] = [\n"
        + "\n".join(groups)
        + "\n] as const;\n\n"
        "export const JOB_TOOL_NAMES = new Set(\n"
        "  JOB_TOOL_DESCRIPTORS.map(descriptor => descriptor.name),\n"
        ");\n"
    )


def _catalogue() -> str:
    lines = [
        "<!-- Generated by scripts/generate-job-surface.py; do not edit. -->",
        "",
        "# Job tool catalogue",
        "",
        "| Name | Group | Plane | Caller defaults | Grant |",
        "|---|---|---|---|---|",
    ]
    for item in JOB_DESCRIPTORS:
        lines.append(
            f"| `{item.name}` | `{item.group}` | `{item.plane}` | "
            f"{', '.join(f'`{value}`' for value in sorted(item.caller_defaults))} | "
            f"{f'`{item.grant}`' if item.grant else 'category default'} |"
        )
    lines.append("")
    return "\n".join(lines)


def _artifacts() -> dict[Path, str]:
    return {TS_PATH: _typescript(), CATALOGUE_PATH: _catalogue()}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when a committed artifact is stale",
    )
    args = parser.parse_args()

    # The catalogue lives in the private design vault, which is a separate
    # nested clone. Guard before mkdir: without this, a vault-less machine
    # would fabricate a bare knowledge-base/ tree that belongs to no repo and
    # silently write the catalogue into a gitignored void.
    vault = ROOT / "knowledge-base"
    stale: list[Path] = []
    for path, expected in _artifacts().items():
        if path.is_relative_to(vault) and not (vault / ".git").exists():
            raise SystemExit(
                f"{path.relative_to(ROOT)} lives in the design vault, but "
                "knowledge-base/ is not cloned here. Clone it first — see "
                "AGENTS.md, 'Design vault'."
            )
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == expected:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")

    if stale:
        rendered = ", ".join(str(path) for path in stale)
        raise SystemExit(
            f"generated job-surface artifacts are stale: {rendered}; "
            "run scripts/generate-job-surface.py"
        )


if __name__ == "__main__":
    main()
