-- migration:     0067_db_backed_default_expert_pointers.sql
-- description:   Application/personal default expert pointers and append-only
--                audit records. Typed composite FKs prevent cross-mode links.
-- depends-on:    0064_db_backed_default_expert_columns.sql
-- expected:      < 1s (new empty tables only).
-- locks:         new tables only.
-- transactional: yes

BEGIN;
SET LOCAL lock_timeout                        = '2s';
SET LOCAL statement_timeout                   = '15min';
SET LOCAL idle_in_transaction_session_timeout = '5min';

CREATE TABLE IF NOT EXISTS application_expert_defaults (
    expert_type VARCHAR(10) PRIMARY KEY
        CHECK (expert_type IN ('worker', 'session')),
    expert_id   UUID NOT NULL,
    updated_by  UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT application_expert_defaults_expert_type_fkey
        FOREIGN KEY (expert_id, expert_type)
        REFERENCES experts(id, expert_type) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS user_expert_defaults (
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expert_type VARCHAR(10) NOT NULL
        CHECK (expert_type IN ('worker', 'session')),
    expert_id   UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, expert_type),
    CONSTRAINT user_expert_defaults_expert_type_fkey
        FOREIGN KEY (expert_id, expert_type)
        REFERENCES experts(id, expert_type) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS expert_default_audit (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
    target_user_id    UUID REFERENCES users(id) ON DELETE SET NULL,
    target_project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
    expert_type       VARCHAR(10) NOT NULL
        CHECK (expert_type IN ('worker', 'session')),
    scope_kind        VARCHAR(20) NOT NULL
        CHECK (scope_kind IN ('application', 'user', 'project', 'managed')),
    old_expert_id     UUID,
    new_expert_id     UUID,
    action            VARCHAR(20) NOT NULL
        CHECK (action IN ('set', 'clear', 'seed', 'update')),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE application_expert_defaults IS
    'Exactly one DB expert selected by the operator for each root creation type.';
COMMENT ON TABLE user_expert_defaults IS
    'Optional user-owned default expert per type; use is gated at resolution time.';

COMMIT;
