// website/generator.mjs — pure, DOM-free generator. Ships to the browser AND
// imported by the Node test suite. Zero dependencies; uses the global Web Crypto
// API (browsers + Node >=20). The drift-gate (website/test/generator.drift.test.mjs)
// proves the output renders against the real chart.
export const PROFILES = ['evaluation', 'production', 'production-vms'];

const CHART = 'oci://ghcr.io/knaeckebrothero/charts/superhuman-remote-worker';

export function randomHex(nBytes) {
  const b = new Uint8Array(nBytes);
  globalThis.crypto.getRandomValues(b);
  return [...b].map((x) => x.toString(16).padStart(2, '0')).join('');
}

export function generate(profile, inputs) {
  if (!PROFILES.includes(profile)) throw new Error(`unknown profile: ${profile}`);
  return {
    valuesYaml: buildValuesYaml(profile, inputs),
    secretSkeleton: buildSecret(profile, inputs),
    installScript: buildInstall(profile, inputs),
  };
}

function buildValuesYaml(profile, inputs) {
  const L = [];
  L.push('# Generated by the SRW config generator — review every value before installing.');
  L.push(`# Profile: ${profile}`);
  L.push('license:');
  L.push(`  acceptTerms: ${inputs.licenseAccepted === true}`);
  L.push('');
  L.push('global:');
  L.push(`  domain: "${inputs.domain}"`);
  L.push('');

  if (profile === 'evaluation') {
    L.push('# Eval/single-node: chart-created secrets (dev/eval only).');
    L.push('secrets:');
    L.push('  create: true');
    L.push('  values: {}');
    L.push('');
  } else {
    L.push('secrets:');
    L.push('  existingSecret: srw-secrets');
    L.push('');
    const ext = nonDbExternalBlock(inputs);
    if (ext.length) L.push(...ext, '');
  }

  L.push(...databasesBlock(profile, inputs), '');

  L.push('ingress:');
  L.push('  enabled: true');
  L.push(`  className: ${inputs.ingressClass}`);
  L.push('  tls:');
  L.push(`    enabled: ${inputs.tlsEnabled === true}`);
  if (inputs.tlsEnabled) L.push(`    issuerName: ${inputs.tlsIssuer || 'letsencrypt-prod'}`);
  L.push('');

  if (profile === 'production-vms') L.push(...vmControllerBlock(inputs), '');

  return L.join('\n') + '\n';
}

// Emits the `databases:` section exactly once: external DB entries (production
// profiles, when bring-your-own) followed by neo4j (always).
function databasesBlock(profile, inputs) {
  const L = ['databases:'];
  if (profile !== 'evaluation') {
    const dbExt = (key, svc, url) => inputs[svc] === 'external' ? [
      `  ${key}:`, '    enabled: true', '    internal: false', `    externalUrl: "${url}"`,
    ] : [];
    L.push(...dbExt('postgres', 'postgres', inputs.postgresUrl));
    L.push(...dbExt('vector', 'vector', inputs.vectorUrl));
    L.push(...dbExt('mongodb', 'mongodb', inputs.mongodbUrl));
  }
  L.push('  neo4j:');
  L.push(`    enabled: ${inputs.neo4jEnabled === true}`);
  if (inputs.neo4jEnabled) {
    L.push(`    edition: ${inputs.neo4jEdition || 'community'}`);
    if (inputs.neo4jEdition === 'enterprise') L.push('    acceptLicense: "yes"');
  }
  return L;
}

// Non-database external services (production profiles): OIDC, git, cloud storage.
function nonDbExternalBlock(inputs) {
  const L = [];
  const ext = (svc) => inputs[svc] === 'external';
  if (ext('oidc')) {
    L.push('keycloak:', '  enabled: true', '  internal: false',
      `  externalIssuerUrl: "${inputs.oidcIssuerUrl}"`,
      `  cockpitClientId: "${inputs.cockpitClientId || 'srw-cockpit'}"`,
      '  adminApiDisabled: true');
  }
  if (ext('git')) {
    if (L.length) L.push('');
    L.push('gitea:', '  enabled: true', '  internal: false',
      `  internalUrl: "${inputs.gitUrl}"`, `  externalUrl: "${inputs.gitUrl}"`);
  }
  if (ext('cloud')) {
    if (L.length) L.push('');
    L.push('opencloud:', '  enabled: false', 'nextcloud:', '  enabled: false',
      'cloud:', `  externalBackend: "${inputs.cloudBackend || 'nextcloud'}"`,
      `  externalUrl: "${inputs.cloudUrl}"`, `  externalServiceUrl: "${inputs.cloudUrl}"`);
  }
  return L;
}

function vmControllerBlock(inputs) {
  const vm = inputs.vm || {};
  return [
    'vmController:',
    '  enabled: true',
    `  transport: ${vm.transport || 'http'}`,
    `  namespace: ${vm.namespace || 'agent-vms'}`,
    `  vmStorageClass: ${vm.storageClass || 'longhorn'}`,
    `  vmDiskSize: ${vm.diskSize || '30Gi'}`,
    `  vmSshPublicKey: "${vm.sshPublicKey || ''}"`,
  ];
}

// Filled in by later tasks (Secret skeleton, install script):
function buildSecret() { return ''; }
function buildInstall() { return ''; }

export { CHART };
