// website/generator.mjs — pure, DOM-free generator. Ships to the browser AND
// imported by the Node test suite. Zero dependencies; uses the global Web Crypto
// API (browsers + Node >=20). The drift-gate (website/test/generator.drift.test.mjs)
// proves the output renders against the real chart.
export const PROFILES = ['evaluation', 'production', 'production-vms'];

const CHART = 'oci://ghcr.io/knaeckebrothero/charts/superhuman-remote-worker';

export function randomHex(nBytes) {
  const b = new Uint8Array(nBytes);
  globalThis.crypto.getRandomValues(b);
  return [...b].map((x) => x.toString(16).padStart(2, '0')).join('');
}

export function generate(profile, inputs) {
  if (!PROFILES.includes(profile)) throw new Error(`unknown profile: ${profile}`);
  return {
    valuesYaml: buildValuesYaml(profile, inputs),
    secretSkeleton: buildSecret(profile, inputs),
    installScript: buildInstall(profile, inputs),
  };
}

// Enum constraints mirrored from helm/values.schema.json (structural) plus a
// couple the chart enforces via template guards. The unit test asserts every
// schema enum is covered here.
const ENUMS = {
  ingressClass: ['nginx', 'traefik'],
  'databases.neo4j.edition': ['community', 'enterprise'],
  'vmController.transport': ['http', 'nats', 'both'],
  'cloud.externalBackend': ['nextcloud', 'opencloud', 'webdav'],
};

// Returns [] when valid, else human-readable error strings. Mirrors the chart's
// required/fail guards (license, external-service URLs, neo4j-enterprise license,
// nats transport enum) — the cross-field semantics values.schema.json omits.
export function validate(profile, inputs) {
  const e = [];
  if (inputs.licenseAccepted !== true) e.push('You must accept the license terms.');
  if (!inputs.domain || !/^[a-z0-9.-]+\.[a-z]{2,}$/i.test(inputs.domain))
    e.push('A valid base domain is required.');
  if (inputs.ingressClass && !ENUMS.ingressClass.includes(inputs.ingressClass))
    e.push('Ingress class must be nginx or traefik.');

  if (profile !== 'evaluation') {
    for (const svc of ['postgres', 'vector']) {
      if (inputs[svc] === 'external' && !inputs[svc + 'Host']) e.push(`An external ${svc} requires its host.`);
    }
    for (const [svc, url] of [['mongodb', 'mongodbUrl'], ['git', 'gitUrl'], ['cloud', 'cloudUrl']]) {
      if (inputs[svc] === 'external' && !inputs[url]) e.push(`An external ${svc} requires its URL.`);
    }
    if (inputs.oidc === 'external' && !inputs.oidcIssuerUrl)
      e.push('An external OIDC provider requires its issuer URL.');
  }
  if (inputs.neo4jEnabled && inputs.neo4jEdition === 'enterprise' && inputs.neo4jLicenseAccepted === false)
    e.push('Neo4j Enterprise requires accepting its license.');
  if (profile === 'production-vms' && inputs.vm?.transport
      && !ENUMS['vmController.transport'].includes(inputs.vm.transport))
    e.push('VM transport must be http, nats, or both.');
  return e;
}

function buildValuesYaml(profile, inputs) {
  const L = [];
  L.push('# Generated by the SRW config generator — review every value before installing.');
  L.push(`# Profile: ${profile}`);
  L.push('license:');
  L.push(`  acceptTerms: ${inputs.licenseAccepted === true}`);
  L.push('');
  L.push('global:');
  L.push(`  domain: "${inputs.domain}"`);
  L.push('');

  if (profile === 'evaluation') {
    L.push('# Eval/single-node: chart-created secrets (dev/eval only).');
    L.push('secrets:');
    L.push('  create: true');
    L.push('  values: {}');
    L.push('');
  } else {
    L.push('secrets:');
    L.push('  existingSecret: srw-secrets');
    L.push('');
    const ext = nonDbExternalBlock(inputs);
    if (ext.length) L.push(...ext, '');
  }

  L.push(...databasesBlock(profile, inputs), '');

  L.push('ingress:');
  L.push('  enabled: true');
  L.push(`  className: ${inputs.ingressClass}`);
  L.push('  tls:');
  L.push(`    enabled: ${inputs.tlsEnabled === true}`);
  if (inputs.tlsEnabled) L.push(`    issuerName: ${inputs.tlsIssuer || 'letsencrypt-prod'}`);
  L.push('');

  if (profile === 'production-vms') L.push(...vmControllerBlock(inputs), '');

  return L.join('\n') + '\n';
}

// Emits the `databases:` section exactly once: external DB entries (production
// profiles, when bring-your-own) followed by neo4j (always).
function databasesBlock(profile, inputs) {
  const L = ['databases:'];
  if (profile !== 'evaluation') {
    // Postgres + vector take discrete host/port/db (the chart composes the DSN at
    // runtime with creds from the Secret). Only mongodb takes a full externalUrl.
    const pgExt = (key, svc, defaultDb) => inputs[svc] === 'external' ? [
      `  ${key}:`, '    enabled: true', '    internal: false',
      `    externalHost: "${inputs[svc + 'Host'] || ''}"`,
      `    externalPort: ${inputs[svc + 'Port'] || 5432}`,
      `    externalDb: "${inputs[svc + 'Db'] || defaultDb}"`,
    ] : [];
    L.push(...pgExt('postgres', 'postgres', 'srw'));
    L.push(...pgExt('vector', 'vector', 'srw_vector'));
    if (inputs.mongodb === 'external') {
      L.push('  mongodb:', '    enabled: true', '    internal: false',
        `    externalUrl: "${inputs.mongodbUrl || ''}"`);
    }
  }
  L.push('  neo4j:');
  L.push(`    enabled: ${inputs.neo4jEnabled === true}`);
  if (inputs.neo4jEnabled) {
    L.push(`    edition: ${inputs.neo4jEdition || 'community'}`);
    if (inputs.neo4jEdition === 'enterprise') L.push('    acceptLicense: "yes"');
  }
  return L;
}

// Non-database external services (production profiles): OIDC, git, cloud storage.
function nonDbExternalBlock(inputs) {
  const L = [];
  const ext = (svc) => inputs[svc] === 'external';
  if (ext('oidc')) {
    L.push('keycloak:', '  enabled: true', '  internal: false',
      `  externalIssuerUrl: "${inputs.oidcIssuerUrl}"`,
      `  cockpitClientId: "${inputs.cockpitClientId || 'srw-cockpit'}"`,
      '  adminApiDisabled: true');
  }
  if (ext('git')) {
    if (L.length) L.push('');
    L.push('gitea:', '  enabled: true', '  internal: false',
      `  internalUrl: "${inputs.gitUrl}"`, `  externalUrl: "${inputs.gitUrl}"`);
  }
  if (ext('cloud')) {
    if (L.length) L.push('');
    L.push('opencloud:', '  enabled: false', 'nextcloud:', '  enabled: false',
      'cloud:', `  externalBackend: "${inputs.cloudBackend || 'nextcloud'}"`,
      `  externalUrl: "${inputs.cloudUrl}"`, `  externalServiceUrl: "${inputs.cloudUrl}"`);
  }
  return L;
}

function vmControllerBlock(inputs) {
  const vm = inputs.vm || {};
  return [
    'vmController:',
    '  enabled: true',
    `  transport: ${vm.transport || 'http'}`,
    `  namespace: ${vm.namespace || 'agent-vms'}`,
    `  vmStorageClass: ${vm.storageClass || 'longhorn'}`,
    `  vmDiskSize: ${vm.diskSize || '30Gi'}`,
    `  vmSshPublicKey: "${vm.sshPublicKey || ''}"`,
  ];
}

// Secret keys for the operator-owned-Secret profiles. GENERATED keys get a
// random value (internal secrets); USER_KEYS get CHANGE_ME placeholders (or
// filled values when fillSecrets). These mirror the chart's non-optional
// secretKeyRefs for the recommended (external-services) config — the drift-gate
// (generator.drift.test.mjs) fails CI if the chart references a key not listed
// here. NOTE: GITEA_ADMIN_* are referenced unconditionally by the chart even
// with external git (a documented stub-key requirement), so they must be present.
const GENERATED = ['APP_ENCRYPTION_KEY', 'MCP_INTERNAL_KEY'];
const USER_KEYS = {
  evaluation: [],
  production: ['POSTGRES_USER', 'POSTGRES_PASSWORD',
               'VECTOR_POSTGRES_USER', 'VECTOR_POSTGRES_PASSWORD',
               'AUDIT_POSTGRES_USER', 'AUDIT_POSTGRES_PASSWORD',
               'KC_CLIENT_SECRET', 'GITEA_ADMIN_USER', 'GITEA_ADMIN_PASSWORD'],
};
USER_KEYS['production-vms'] = USER_KEYS.production;

function buildSecret(profile, inputs) {
  if (profile === 'evaluation') {
    return ['# Eval mode: the chart creates the Secret and auto-generates the',
      '# required keys (APP_ENCRYPTION_KEY etc.). No Secret to pre-create — add',
      '# provider API keys after install via Admin → Providers.'].join('\n') + '\n';
  }
  const val = (k) => (inputs.fillSecrets && inputs.secretValues?.[k]) || 'CHANGE_ME';
  const data = {};
  for (const k of GENERATED) data[k] = randomHex(32);     // random internal secrets
  for (const k of USER_KEYS[profile]) data[k] = val(k);

  const lines = ['# Pre-create this Secret before `helm install`. Every key below is',
    '# referenced by the chart; set real values (or safe dummies for components you',
    '# run externally, e.g. GITEA_ADMIN_* when using external git).',
    'apiVersion: v1', 'kind: Secret', 'metadata:',
    '  name: srw-secrets', '  namespace: srw', 'type: Opaque', 'stringData:'];
  for (const [k, v] of Object.entries(data)) lines.push(`  ${k}: ${v}`);
  return lines.join('\n') + '\n';
}

function buildInstall(profile) {
  const L = ['#!/usr/bin/env bash', 'set -euo pipefail', '',
    '# Generated by the SRW config generator. Review before running.',
    '# Prereqs: a working cluster + kubectl/helm context, DNS + TLS per the install guide.',
    '', 'kubectl create namespace srw --dry-run=client -o yaml | kubectl apply -f -'];
  if (profile !== 'evaluation') L.push('kubectl apply -n srw -f srw-secrets.yaml');
  L.push('', `helm install srw ${CHART} \\`, '  -n srw \\', '  -f values.yaml');
  return L.join('\n') + '\n';
}

export { CHART };
